.travis.yml

This PR will add automatic builds and tests run in `node@4`, `node@6`, and `node@lts` for every push and every pull request.
And holy cow was it easy to set up.  Thanks, Travis! ❤️

Add Travis CI integration for automatic builds & tests

---

src/Lexer.ts

Finally!  What took you so long, @sjbarag?

(lex) Add documentation for Lexer

---

src/index.ts
src/lexer/Characters.ts
src/lexer/index.ts
test/Lexer.test.js

These functions all deal with characters, so `Characters` feels reasonable.

(lex) Move lexer helper functions to a util file

---

src/index.ts
src/parser/Expression.ts
src/visitor/AstPrinter.ts
src/visitor/Executioner.ts
src/visitor/index.ts
test/executioner/Arithmetic.test.js

A programming language isn't very useful if it just produces an abstract syntax tree.  Let's evaluate that tree!  BRS is now a functioning (but _very_ simple) interpreter that supports:
1. Arithmetic:
* Addition
* Subtraction
* Multiplication
* Division
* Integer division
* Modulo operations
* Exponentiation
* Parenthetic grouping
2. Boolean logic:
* And/or/not of booleans
3. Comparisons
* Less-than, less-than-or-equal, greater-than, greater-than-or-equal, equal, and non-equal
The REPL works pretty well, but because there's no `print` statement yet executing a file doesn't actually produce anything.

(exec) Add execution stage

---

src/Error.ts
src/parser/index.ts
src/visitor/Executioner.ts
test/executioner/Arithmetic.test.js
test/executioner/BooleanAlgebra.test.js
test/parser/Boolean.test.js
test/parser/__snapshots__/Boolean.test.js.snap

I forgot to wire up the `and` and `or` operators in the first round of the interpreter.  This fixes that, but doesn't fix the fact that I'm a derp.
Sadly, there's no fix for my derpiness 😞

(exec) Execute boolean expressions

---

src/index.ts
test/e2e/EndToEnd.test.js
test/e2e/resources/arithmetic.brs
test/e2e/resources/assignment.brs
test/e2e/resources/comments.brs
test/e2e/resources/conditionals.brs
test/e2e/resources/printLiterals.brs

End to end tests are really helpful, since they let us verify the `brs` interpreter as a regular user would.  Plus we can start comparing behavior to an actual Roku device.

feat: Add end to end tests

---

package.json
yarn.lock

This should keep me from publishing the wrong code.  Not that that's happened yet.

fix(build): Clean, build, and test before publishing

---

README.md

Also nice to clarify how to clean, build, and test in one command without shell conditionals.

fix(docs): Clarify that _this project_ is TS, not `yarn`

---

src/interpreter/index.ts
src/stdlib/String.ts
test/e2e/StdLib.test.js
test/e2e/resources/stdlib/strings.brs
test/stdlib/String.test.js

Hey Sean, this project is really cool!!!  Disclaimer that I basically still don't have a clue what I'm really doing, so I apologize for all the noob mistakes and questions I'm making (and will be making).
I just wanted to send this short PR out to get my feet wet, I know there are Mid() and Right() functions left to do, they'll be done separately.
contributes to #49

Implement global string function Left()

---

.gitignore
src/interpreter/index.ts
src/stdlib/String.ts
test/e2e/StdLib.test.js
test/e2e/resources/stdlib/strings.brs
test/stdlib/String.test.js

I did not comment on the issue and I did not finish all of the String functions, but I wanted to help out this project.
I have added Right, Mid, Len, and Instr. I have added tests around some basic functionality with those functions. I hope this helps and I welcome all feedback.
I also added `.idea/` to `.gitignore` since I use WebStorm for development.

Added some String Global Functions

---

src/interpreter/index.ts
src/stdlib/String.ts
test/e2e/StdLib.test.js
test/e2e/resources/stdlib/strings.brs
test/stdlib/String.test.js

Substitute looks like it's the last string function to implement to close #44 and close #51.

implement Substitute function (issue #51)

---

src/brsTypes/BrsType.ts
src/brsTypes/components/AssociativeArray.ts
src/brsTypes/components/BrsArray.ts
src/brsTypes/components/BrsComponent.ts
src/brsTypes/components/BrsObjects.ts
src/brsTypes/index.ts
src/interpreter/index.ts
src/stdlib/CreateObject.ts
src/stdlib/File.ts
src/stdlib/Type.ts
test/brsTypes/BrsObjects.test.js
test/brsTypes/components/Array.test.js
test/brsTypes/components/AssociativeArray.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roArray.brs
test/interpreter/Call.test.js
test/stdlib/Runtime.test.js

The [ifArray](https://sdkdocs.roku.com/display/sdkdoc/ifArray) interface provides a bunch of very useful methods for working with arrays.  This PR sets up the basics needed to implement methods on a BrightScript Component, and implements some of them on the "roArray" component.

feat(stdlib): Implement ifArray on array types

---

bin/cli.js
package.json
src/index.ts
src/interpreter/index.ts
test/e2e/resources/components/roArray.brs
test/e2e/resources/function/m-pointer.brs
test/e2e/resources/function/scoping.brs
test/e2e/resources/multi-file/test2.brs
test/e2e/resources/stdlib/runtime.brs
test/interpreter/FunctionDeclaration.test.js
yarn.lock

C, Java, and a bunch of other languages automatically call a function called `main`.  The Reference BrightScript Implementation also does, so we should as well.  Now we've got a consistent entry point, and a manual call to `Main` isn't required anymore!

feat(interp): Automatically call main() function

---

README.md

Show status badges for build and npm. This helps users quickly see if the project is stable, and also see the latest npm verison without having to manually search npm for the project.

Added build and npm status badges

---

src/parser/Parser.ts

Fixed spelling mistake in "Expected identifier" error.

---

src/brsTypes/Int32.ts
src/brsTypes/Int64.ts
src/lexer/Characters.ts
src/lexer/Lexer.ts
test/brsTypes/Int32.test.js
test/brsTypes/Int64.test.js
test/e2e/Syntax.test.js
test/e2e/resources/printLiterals.brs
test/lexer/Lexer.test.js

This has been a "todo" for _far_ too long!
fixes #199

feat(lex,types,e2e): Add support for hex literals

---

.circleci/config.yml
bin/cli.js
package.json
src/brsTypes/components/Regex.ts
src/index.ts
src/lexer/Lexer.ts
src/parser/Parser.ts
src/preprocessor/Manifest.ts
test/cli/cli.test.js
test/e2e/Brs.test.js
test/e2e/BrsComponents.test.js
test/e2e/ConditionalCompilation.test.js
test/e2e/Functions.test.js
test/e2e/Iterables.test.js
test/e2e/StdLib.test.js
test/e2e/Syntax.test.js
test/preprocessor/Manifest.test.js
tsconfig.json
yarn.lock

Now that node 6 has been deprecated, we can start using async/await in tests!  :tada:

chore(build): Drop support for node 6

---

yarn.lock

Not much else to say here :man_shrugging:

chore(deps): Upgrade dependencies

---

src/brsTypes/components/BrsObjects.ts
src/brsTypes/components/RoAssociativeArray.ts
src/brsTypes/components/RoSGNode.ts
src/brsTypes/index.ts
test/brsTypes/components/RoAssociativeArray.test.js
test/brsTypes/components/RoSGNode.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roAssociativeArray.brs
test/e2e/resources/components/roSGNode.brs

This implements RoSGNode--specifically the ifAssociativeArray interface.  This is almost a straight copy of the roAssociativeArray implementation, which will serve as a foundation for future interfaces such as supporting fields.  While some of the code might be shareable between them in the Node's current state, I imagine the Node implementation will have a lot of special cases to handle fields, so these functions are placeholders for future interfaces, which will slightly modify their behavior.

rough implementation of RoSGNode/ifAssociativeArray

---

src/brsTypes/components/RoSGNode.ts
src/interpreter/Environment.ts
src/interpreter/index.ts
test/brsTypes/components/RoSGNode.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roSGNode.brs

This implements all the interfaces of `ifSGNodeFocus` on RoSGNode:
- hasFocus()
- setFocus()
- isInFocusChain()

Implement if sg node focus

---

bin/cli.js
src/index.ts

Added "quit" and "exit" cli statements and fixed "invalid" message  #272 #273

---

test/parser/statement/Block.test.js

chore(test): Remove spurious console.log

---

src/brsTypes/BrsNumber.ts
src/brsTypes/Double.ts
src/brsTypes/Float.ts
src/brsTypes/Int32.ts
src/brsTypes/Int64.ts
src/interpreter/index.ts
src/parser/Parser.ts
test/e2e/Syntax.test.js
test/e2e/resources/arithmetic.brs
test/interpreter/Arithmetic.test.js

Bitshift operations

---

src/brsTypes/BrsType.ts
src/brsTypes/Double.ts
src/brsTypes/Float.ts
src/brsTypes/Int32.ts
src/brsTypes/components/BrsObjects.ts
src/brsTypes/components/RoBoolean.ts
src/brsTypes/components/RoDouble.ts
src/brsTypes/components/RoFloat.ts
src/brsTypes/components/RoInt.ts
src/brsTypes/index.ts
test/brsTypes/components/RoBoolean.test.js
test/brsTypes/components/RoDouble.test.js
test/brsTypes/components/RoFloat.test.js
test/brsTypes/components/RoInt.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roIntrinsics.brs

This PR implements the following components:
- roBoolean
- roDouble
- roFloat
- roInt

feat(stdlib): Implement roBoolean, roDouble, roFloat, roInt

---

src/lexer/Lexer.ts
test/lexer/Lexer.test.js
test/parser/statement/__snapshots__/Misc.test.js.snap

Support rem as an object property

---

src/interpreter/Environment.ts
src/stdlib/index.ts
test/e2e/Functions.test.js
test/e2e/resources/function/m-pointer-global.brs
test/interpreter/Environment.test.js

feat(stdlib): Implement GetGlobalAA() runtime function

---

src/brsTypes/components/RoString.ts
test/brsTypes/components/RoString.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roString.brs

I forgot about these, whoops!
fixes #361

feat(stdlib): Implement getString() and toStr() on RoString

---

src/brsTypes/components/RoSGNode.ts
test/brsTypes/components/RoSGNode.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roSGNode.brs

See issue https://github.com/sjbarag/brs/issues/378
fixes #378

feat(stdlib): Implement roSGNode#update second parameter

---

src/lexer/Lexer.ts
test/lexer/Lexer.test.js

Fix lex issue with `#ELSE IF` and `#END IF`

---

src/brsTypes/components/ComponentFactory.ts
src/brsTypes/components/Label.ts
src/brsTypes/components/RoSGNode.ts
src/brsTypes/index.ts
test/brsTypes/components/Label.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/Label.brs
test/e2e/resources/components/Label.xml

This implements the `<Label>` component.

Implement Label component

---

src/stdlib/GlobalUtilities.ts
test/e2e/StdLib.test.js
test/e2e/resources/stdlib/global-utilities.brs
test/stdlib/GlobalUtilities.test.js

FindMemberFunction can now be used on `brs`
fixes #78

feat(stdlib): Added support for FindMemberFunction

---

src/brsTypes/BrsType.ts
src/brsTypes/components/ComponentFactory.ts
src/brsTypes/components/Font.ts
src/brsTypes/index.ts
test/brsTypes/components/Font.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/ComponentsAsChildren.xml
test/e2e/resources/components/Font.brs

This implements the `<Font>` component.

feat(stdlib): implement Font component

---

src/brsTypes/components/ComponentFactory.ts
src/brsTypes/components/Poster.ts
src/brsTypes/index.ts
test/brsTypes/components/Poster.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/ComponentsAsChildren.xml
test/e2e/resources/components/Poster.brs

This implements the `<Poster>` component.

feat(stdlib): implement Poster component

---

src/brsTypes/components/ComponentFactory.ts
src/brsTypes/components/LayoutGroup.ts
src/brsTypes/index.ts
test/brsTypes/components/LayoutGroup.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/ComponentsAsChildren.xml
test/e2e/resources/components/LayoutGroup.brs

This implements the `<LayoutGroup>` component.

feat(stdlib): implement LayoutGroup component

---

src/brsTypes/components/RoSGNode.ts
src/componentprocessor/index.ts
src/interpreter/Environment.ts
test/e2e/BrsComponents.test.js
test/e2e/resources/components/FieldChangeComponent.xml
test/e2e/resources/components/FieldChangeParent.xml
test/e2e/resources/components/NormalWidget.xml
test/e2e/resources/components/scripts/BaseWidget.brs
test/e2e/resources/components/scripts/FieldChangeComponent.brs
test/e2e/resources/components/scripts/FieldChangeParent.brs
test/e2e/resources/components/scripts/FieldChangeRunner.brs

This finishes wiring up the `onChange` callbacks. A lot of the work was already there; this PR just modifies the calling pattern so that the correct environment is being used for the callbacks.

On-change callbacks

---

src/brsTypes/components/RoSGNode.ts
src/componentprocessor/index.ts
test/e2e/BrsComponents.test.js
test/e2e/resources/components/CallFuncComponent.xml
test/e2e/resources/components/scripts/CallFuncComponent.brs
test/e2e/resources/components/scripts/CallFuncMain.brs

This implements `callFunc` and closes #388.

feat(stdlib): implement callFunc

---

bin/cli.js

Just a strawman feature, nothing to see here.

fix(cli): Improve the description

---

src/brsTypes/components/ComponentFactory.ts
src/brsTypes/components/Timer.ts
src/brsTypes/index.ts
test/brsTypes/components/Timer.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/Timer.brs

This change implements the SceneGraph [`Timer`](https://developer.roku.com/docs/references/scenegraph/control-nodes/timer.md) component.

feat(stdlib): Implement Timer Component

---

.circleci/config.yml
.github/workflows/nightly-build.yaml

🤔 not sure if this will trigger while it's still in a PR; we'll see!

chore(ci): Migrate nightly builds to GitHub Actions

---

.github/workflows/nightly-build.yaml

Looks like the issue was mostly me manually setting CI=true via the `.env` block?  :shrug:

fix(ci): Make nightly builds actually work

---

src/brsTypes/components/RoSGNode.ts
test/e2e/NestedInlineChildren.test.js
test/e2e/resources/components/NestedInlineChildren.xml
test/e2e/resources/components/scripts/NestedInlineChildren.brs
test/e2e/resources/components/scripts/NestedInlineChildrenMain.brs

fix(stdlib): Create nested children correctly

---

package.json

Release 0.27.0

---

src/brsTypes/components/RoAssociativeArray.ts
test/brsTypes/components/RoAssociativeArray.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roAssociativeArray.brs

Added support for `setModeCaseSensitive` for `roAssociativeArray` as it was missing in the `ifAssociativeArray` interface

feat(stdlib): Added case sensitive support to roAssociativeArray

---

src/brsTypes/components/RoSGNode.ts
test/brsTypes/components/RoSGNode.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roSGNode/roSGNode.brs

feat(scenegraph): Implement ifSGNodeField#getFields()

---

src/parser/Parser.ts
test/parser/controlFlow/__snapshots__/If.test.js.snap
test/parser/statement/__snapshots__/Block.test.js.snap

This adds support for the parser to record the `else` token location.

fix(parser): add else token

---

src/brsTypes/components/RoRegex.ts
test/e2e/BrsComponents.test.js
test/e2e/resources/components/roRegex.brs

fix(stdlib): RoRegex captures groups

---

README.md
package.json
src/brsTypes/components/RoSGNode.ts
src/extensions/index.ts
src/extensions/triggerKeyEvent.ts
test/e2e/KeyEvent.test.js
test/e2e/resources/components/key-events/KeyEvents.brs
test/e2e/resources/components/key-events/KeyEvents_Child.xml
test/e2e/resources/components/key-events/KeyEvents_Grandparent.xml
test/e2e/resources/components/key-events/KeyEvents_Parent.xml
test/e2e/resources/components/key-events/main.brs
yarn.lock

This implements a `_brs_.triggerKeyEvent`, which will send key events up the focus chain until it's handled.

feat(ext): implement brs#triggerKeyEvent

---

src/brsTypes/components/RoSGNode.ts
test/brsTypes/components/RoSGNode.test.js
test/e2e/BrsComponents.test.js
test/e2e/resources/components/scripts/ExtendedComponent.brs

Solves https://github.com/sjbarag/brs/issues/582

feat(rsg): Add isSubtype() and parentSubtype() functions to RoSGNode

---

.github/workflows/nightly-build.yaml

I negated all of those `if` properties.  Whooooops

fix(infra): build and publish if there are commits since last night
