sjbarag/brs

- package.json
- src/Lexeme.ts
- src/Lexer.ts
- src/Token.ts
- test/Lexer.js
- yarn.lock
Still need to work out hexadecimal literals, but this includes:
1. Double-precision floats
2. Single-precision floats
3. 64-bit integers
4. 32-bit integers
I'm _pretty sure_ I got the rules right from the BrightScript spec?
https://sdkdocs.roku.com/display/sdkdoc/Expressions%2C+Variables%2C+and+Types#Expressions,Variables,andTypes-NumericLiterals
> (lex) Add support for numeric literals

- src/Lexer.ts
I couldn't find any docs on this, but verified on a Roku.  
```
a = 1.23456789D+12 
b = 1.23456789D-12 
c = 1.23456789D12 
d = 1.23456789E+12 
e = 1.23456789E-12 
f = 1.23456789E12 
?type(a)
?type(b)
?type(c)
?type(d)
?type(e)
?type(f)
```
Types and values:
```
Double
Double
Double
Float
Float
Float
```
> removed a couple of verification TODO comments

- package.json
- yarn.lock
The `rimraf` package runs in `node` directly, meaning the `clean` target can now run on Windows platforms.
I don't have a Windows machine handy to test this on, but I'll trust `rimraf` 🤷‍♂️
> (build) Use `rimraf` to clean instead of `rm -rf`

- src/grammar/BrightscriptGrammer.ebnf
**Note: I'm primarily sending out this PR as a talking point to see if you all would be interested in having and iterating on a grammar file. I personally see this as a larger benefit in the medium-long run when we start trying to parse more complicated syntax trees, but I think it could also benefit us these earlier stages as well.** @sjbarag @strattonbrazil 
With that said, I began to lay out some basic brightscript grammar which should be a good base for further iteration and could also possibly help guide the parser's development direction. But depending on how you guys feel, if we are OK with this approach then this should be a good enough base to merge in. But regardless i'm definitely open to hearing what you guys think and answer any questions. For what I _do_ have here I tried to …
> Started defining a formal grammar for brightscript

- README.md
- bin/cli.js
- package.json
- src/Lexer.ts
- src/index.ts
- src/parser/ParseError.ts
- test/parser/Additive.test.js
- test/parser/Exponential.test.js
- test/parser/Multiplicative.test.js
- test/parser/ParserTests.js
- test/parser/Primary.test.js
- test/parser/Relational.test.js
- test/parser/Unary.test.js
`brs` is one fewer character than `orbs`, and matches the BrightScript file extension.  While I love the semantics of `Off Roku BrightScript => orbs`, the `orbs` package is already taken anyway.
so it goes
> (arch) Rename project to "BRS"

- package.json
- src/Token.ts
- src/lexer/index.ts
- test/Lexer.test.js
- yarn.lock
The `long` package includes 64-bit integer arithmetic, but `node-int64` didn't.  Now that we're going to start executing ASTs, we'll need that!
> (arch) Replace node-int64 with long

- src/lexer/index.ts
- test/Lexer.test.js
BrightScript allows the `?` operator to act as a shortcut to the full `print` statement, so our interpreter should do the same.  That means lexing it first.
> (lex) Alias '?' operator to 'print' statement

- src/visitor/Executioner.ts
- test/executioner/Arithmetic.test.js
- test/executioner/Comparison.test.js
- test/executioner/ExecutionerTests.js
I'd previously forgotten to allow mixed-type comparisons and arithmetic, which meant 32-bit integers couldn't be added to 64-bit integers, and they also couldn't be compared.  That's been fixed now!
> fix(exec): Allow mixed-type arithmetic and comparisons

- src/Error.ts
- src/grammar/BrightscriptGrammar.ebnf
- src/index.ts
- src/parser/Statement.ts
- src/parser/index.ts
- src/visitor/Environment.ts
- src/visitor/Executioner.ts
- test/executioner/Variables.test.js
- test/parser/ParserTests.js
- test/parser/statement/Declaration.test.js
- test/parser/statement/__snapshots__/Declaration.test.js.snap
This PR allows users of BRS to create globally-scoped variables, assign values to them, and reference their stored values in other expressions and statements.  It makes `brs` significantly more useful, because it can remember things!
Global variables currently take a copy-value approach, e.g.:
```brightscript
a = 10
b = a
a = 1000
print a     ' 1000
print b     ' 10
print a = b ' false
```
This will likely need to change once we implement associative arrays in BRS, but IIRC "copy-value" is correct for primitive values.
> Add global scope assignments

- src/lexer/index.ts
- test/Lexer.test.js
Completely blank lines are meaningless to the parser, so there's no
sense in passing them along from the lexer into the parser.  We do need
to keep track of line numbers though, and single newline characters are
still significant, so we can't ignore newlines entirely.
fixes #22
> fix(lex,parse): Allow blank lines in executed BrightScript files

- src/parser/index.ts
- test/e2e/EndToEnd.test.js
- test/e2e/resources/conditionals.brs
- test/parser/controlFlow/If.test.js
- test/parser/controlFlow/__snapshots__/If.test.js.snap
The [brs-testbed project](https://github.com/sjbarag/brs-testbed/blob/3218687043eecc11dea57080080f76b983d0d5b4/testfiles/elseif-in-single-line-if.brs) has proven that BrightScript definitely supports 'else if' in single-line if statements.  We should too!
> fix(parse): Allow single-line 'if' to use 'else if'

- src/Token.ts
- src/brsTypes/BrsNumber.ts
- src/brsTypes/Int64.ts
- src/lexer/index.ts
- src/parser/index.ts
- src/visitor/AstPrinter.ts
- src/visitor/Interpreter.ts
- tsconfig.json
- yarn.lock
The most important change here is TypeScript 2.7, which allows the
`esModuleInterop` compiler option.  No more `import = require` for this
repo!
> chore: Upgrade all dependencies to latest versions

- src/Lexeme.ts
- src/index.ts
- src/lexer/index.ts
- src/parser/Statement.ts
- src/parser/index.ts
- src/visitor/Interpreter.ts
- test/Lexer.test.js
- test/e2e/EndToEnd.test.js
- test/e2e/resources/while-loops.brs
- test/interpreter/Arithmetic.test.js
- test/interpreter/BooleanAlgebra.test.js
- test/interpreter/Comparison.test.js
- test/interpreter/If.test.js
- test/interpreter/Variables.test.js
- test/interpreter/While.test.js
- test/parser/__snapshots__/Boolean.test.js.snap
- test/parser/controlFlow/While.test.js
- test/parser/controlFlow/__snapshots__/While.test.js.snap
- test/parser/expression/__snapshots__/Unary.test.js.snap
While loops are necessary for basically every language, because they allow the execution duration of a program to not be bound to the source length of the program.
Also BrightScript on Rou makes heavy use of `while` loops, so we need them too.
> feat: Add while loop support

- src/Lexeme.ts
- src/ReservedWords.ts
- test/Lexer.test.js
While `exitwhile` is a reserved word and is an alias for `exit while`, the same isn't true for `exitfor` and `exit for`.  The only way to exit a `for` loop is with the two-word version "`exit for`".  Odd.
fixes #31
> fix(lex): Don't treat 'exitfor' as a reserved word

- src/Lexeme.ts
- src/ReservedWords.ts
- src/parser/Statement.ts
- src/parser/index.ts
- src/visitor/Environment.ts
- src/visitor/Interpreter.ts
- test/e2e/EndToEnd.test.js
- test/e2e/resources/for-loops.brs
- test/interpreter/For.test.js
- test/interpreter/While.test.js
- test/parser/__snapshots__/Boolean.test.js.snap
- test/parser/controlFlow/For.test.js
- test/parser/controlFlow/__snapshots__/For.test.js.snap
- test/parser/expression/__snapshots__/Unary.test.js.snap
BrightScript has two types of `for` loop: `FOR counter = exp TO exp [STEP exp] (...) END FOR` and `FOR EACH item IN object (...) END FOR`.  Since we don't have an object system yet we can't do `for each`.  But we *can* do `for ... to`!
> feat: Add for/to loops

- bin/cli.js
- src/index.ts
This uses the Promise handling to bubble up file-related problems to the command line handler instead of failing somewhere in the code.  
No arguments:
```
$ brs
brs>
```
Non-existent file:
```
$ brs foo
brs: can't open file 'foo': [Errno -2]
```
Non-readable file:
```
$ brs foo
brs: can't open file 'foo': [Errno -13]
```
Empty file (no error, no output similar to python):
```
$ brs foo
$
```
Confirmed that the cases above have the correct exit code (0 for pass, 1 for failure).
> improved error handling of non-readable input files (issue #21)

- package.json
package.json was pointing at an invalid file for module entry point, which breaks any consumers who require in this module.
> Changes package.json to point at lib/index.js instead of index.js

- test/e2e/StdLib.test.js
- test/e2e/resources/stdlib/strings.brs
- test/stdlib/String.test.js
The actual logic in those functions is already handled in `test/stdlib/Strin.test.js`, so these don't need full coverage. End-to-end tests are helpful here to make sure those functions don't accidentally get removed from global scope :)
> test(stdlib): Add end-to-end tests for Chr and Asc

- src/Error.ts
- src/brsTypes/BrsType.ts
- src/brsTypes/Callable.ts
- src/brsTypes/index.ts
- src/index.ts
- src/interpreter/index.ts
- src/stdlib/String.ts
- src/stdlib/index.ts
- test/brsTypes/Callable.test.js
- test/e2e/TypeChecking.test.js
- test/e2e/resources/type-checking/arg-type-mismatch.brs
- test/e2e/resources/type-checking/too-few-args.brs
- test/e2e/resources/type-checking/too-many-args.brs
- test/interpreter/Call.test.js
- test/stdlib/String.test.js
My use of BrightScript on Roku devices has a rich history of throwing vague `Type mismatch` errors and... well that's about it.  This interpreter needs centralized type checking for function calls, to ensure `brs` don't ungracefully crash when attempting to call `UCase(5)`.  The goal here is to provide more helpful error messages than the reference interpreter though, e.g.:
```
brs> UCase(5)
[line 1] Type mismatch in 'UCase': argument 's' must be of type String, but received Integer.
[Line 1] Type mismatch(es) detected.
brs> 
```
Perhaps I should add in argument indexes too?  Something like "Type mismatch in 'FunctionName': argument n, 'name', must be of type Foo, but received Bar." could be nice.
That can come in a future PR though I imagine :smile: 
fixes #39
> feat(interp,stdlib): Add call-time type checking

- CONTRIBUTING.md
A contributing guide should help people know what's expected of them.  A guide to the project's architecture and layout can come a bit later to help contributors get a lay of the land.
> feat(docs): Add contributing guide

- src/index.ts
- src/interpreter/OutputProxy.ts
- src/interpreter/index.ts
- src/lexer/index.ts
- src/parser/Statement.ts
- src/parser/index.ts
- src/stdlib/Print.ts
- src/stdlib/index.ts
- test/e2e/E2ETests.js
- test/e2e/StdLib.test.js
- test/e2e/Syntax.test.js
- test/e2e/TypeChecking.test.js
- test/e2e/resources/print.brs
- test/interpreter/PrintStatements.test.js
- test/parser/controlFlow/__snapshots__/While.test.js.snap
- test/parser/statement/PrintStatements.test.js
- test/parser/statement/__snapshots__/PrintStatements.test.js.snap
- test/stdlib/Print.test.js
- test/stdlib/String.test.js
Roku's BrightScript [supports printing multiple things with one `print` statement](https://sdkdocs.roku.com/display/sdkdoc/Program+Statements#ProgramStatements-PRINTitemlist), so we should too!  This was surprisingly more difficult than I expected, but a pretty big part of that was making it possible to spy on output without messing with `process.stdout.write`.
Merging this PR will result in the following file being valid according to `brs`:
```brightscript
' All examples inspired by Roku documentation:
' https://sdkdocs.roku.com/display/sdkdoc/Program+Statements#ProgramStatements-PRINTitemlist
' no separators
print "lorem " 1 "psum"
' arbitrary mixes of separators
print 9; " is equal to"; 3^2
print "column a", "column b", "column c", "column d"
' arbitrary tabbing
print tab(3) "I started …
```
> feat(lex,parse,interp,e2e): Implement print lists

- .travis.yml
- package.json
- src/brsTypes/BrsType.ts
- src/brsTypes/Callable.ts
- src/brsTypes/index.ts
- src/index.ts
- src/interpreter/AstPrinter.ts
- src/interpreter/BrsFunction.ts
- src/interpreter/Environment.ts
- src/interpreter/index.ts
- src/lexer/index.ts
- src/parser/BlockEndReason.ts
- src/parser/Statement.ts
- src/parser/index.ts
- src/stdlib/String.ts
- src/stdlib/index.ts
- tsconfig.json
- tslint.json
- yarn.lock
Now `yarn lint` is a valid command, and linting happens automatically during Travis builds.  There's definitely room for improvement here, but this seems like a sensible starting place.
fixes #40
> chore(style,ci): Add tslint to build system

- src/stdlib/String.ts
- test/stdlib/String.test.js
Most of issue #50 has been resolved, but the Val implementation didn't support int conversion.  This is much easier with the default parameter support.  The radix support was extremely simple, because it's handled in much the same way as javascript's parseInt().  For tests I included the examples from the Roku docs as well as the base-10 case.  
NOTE: I have a really cheesy way to detect if a string is a float just be checking for a decimal place.  Open to other ideas.  
Closes #50.
> finishing implementation of Val int conversion

- src/Token.ts
- src/brsTypes/BrsNumber.ts
- src/brsTypes/BrsType.ts
- src/brsTypes/Callable.ts
- src/brsTypes/Double.ts
- src/brsTypes/Float.ts
- src/brsTypes/Int32.ts
- src/brsTypes/Int64.ts
- src/brsTypes/components/AssociativeArray.ts
- src/brsTypes/index.ts
- src/interpreter/AstPrinter.ts
- src/interpreter/index.ts
- src/parser/Expression.ts
- src/parser/index.ts
- test/brsTypes/AssociativeArray.test.js
- test/e2e/Functions.test.js
- test/parser/expression/AssociativeArrayLiterals.test.js
- test/parser/expression/__snapshots__/AssociativeArrayLiterals.test.js.snap
- test/parser/expression/__snapshots__/Function.test.js.snap
- test/parser/statement/__snapshots__/Function.test.js.snap
- test/parser/statement/__snapshots__/ReturnStatement.test.js.snap
This is one of the last steps blocking the start of `CreateObject(objType as string)`, because it allows state to be
stored on a variable.  A few things that haven't been tested against RBI:
1. The maximum size of an associative array
2. The maximum debpth of an associative array
3. Handling of circular references within associative arrays, e.g.:
```brightscript
a = { foo: "bar" }
a.b = a
```
That realistically shouldn't be a huge issue because `print a` would simply list `a.a` as `<Component: roAssociativeArray>`.
This also doesn't have proper handling of the `m` pointer, but that can come next.
> feat(types): Implement AssociativeArrays with dotted and bracketed indexing

- package.json
- src/interpreter/index.ts
- src/stdlib/File.ts
- src/stdlib/index.ts
- test/e2e/StdLib.test.js
- test/e2e/resources/stdlib/files.brs
- test/stdlib/File.test.js
- yarn.lock
This adds the ReadAsciiFile() and WriteAsciiFile() functions to stdlib.  This implementation uses the _memfs_ library so all file operations will be in memory.  This will make working with files safer during brs development.  In the future we can support reading from the hard drive by copying files into the memfs volumes at startup of the interpreter.  
Right now only a single volume, _tmp_, is implemented and is attached to the interpreter object.  In the future we can add additional ones such as _common_ and _package_.  
I've written unit tests for this, but am having trouble with the end-to-end tests for some reason.  
closes #88
> implements file reads/writes using memfs library (#88)

- src/lexer/Lexer.ts
- test/lexer/Lexer.test.js
It's pretty common to use `End Function` instead of `end function` (see: https://github.com/Tubitv/rodash), and they're both valid.  Since RBI supports it, we should too!
closes #96
> fix(lex): Allow `end function` and others to use mixed case

- src/parser/index.ts
- test/parser/controlFlow/If.test.js
- test/parser/controlFlow/__snapshots__/If.test.js.snap
RBI allows 'then' to be dropped and the 'if' statement works the same way.  We should do the same.
fixes #98
> fix(parse): Allow optional 'then' in 'if' statements

- src/interpreter/index.ts
- src/lexer/Lexer.ts
- src/lexer/ReservedWords.ts
- src/lexer/Token.ts
- src/parser/index.ts
- test/interpreter/FunctionDeclaration.test.js
- test/interpreter/Variables.test.js
- test/lexer/Lexer.test.js
There's no need to consider `type` its own token if it's basically just an identifier.  Ditto `createObject`. If these reserved-words-but-not-keywords are treated like regular-old identifiers for most of the parsing logic, we're able to more-easily implement functions like `type`, `createObject`, etc.  Instead of having to check for specific tokens, those can be implemented like regular-old stdlib functions!
Plus now attempting to call `type(foo)` won't result in a parse failure; just a runtime failure because `type` doesn't exist yet :smile:
fixes #80
> fix(lex,parse,interp): Decouple reserved words and keywords

- src/brsTypes/Callable.ts
- src/interpreter/Environment.ts
- src/interpreter/index.ts
- test/e2e/Functions.test.js
- test/e2e/resources/function/m-pointer.brs
- test/interpreter/Call.test.js
- test/interpreter/Environment.test.js
The Reference BrightScript Implementation includes a parallel to JavaScript's `this` variable:
> A BrightScript object is an roAssociativeArray which contains function pointers.  When a member function is called "from" an AssociativeArray, the special variable "m" is set to point to that AssociativeArray. "m" is accessible inside the called function to access other data in the AssociativeArray object.
(https://sdkdocs.roku.com/display/sdkdoc/Component+Architecture#ComponentArchitecture-%22m%22TheBrightScript%22thispointer%22)
This BrightScript implementation needs to have support for it as well.
Depends on #95
> feat(interp,env): Implement `m` pointer

- src/interpreter/index.ts
We had stdlib function names duplicated a whole bunch, and it was really easy to forget to register a stdlib function.  Now it's automatic!  Just export it from `src/stdlib/` and it'll get registered.
> chore(interp): Don't require explicit stdlib registration

- src/brsTypes/components/BrsObjects.ts
- src/brsTypes/index.ts
- src/stdlib/CreateObject.ts
- src/stdlib/index.ts
- test/brsTypes/BrsObjects.test.js
- test/stdlib/CreateObject.test.ts
This implements brightscript's `createObject()` and a new `BrsObjects` map that will contain a list of brightscript components that can be created.
> Implement CreateObject()

- src/interpreter/Environment.ts
- src/interpreter/index.ts
- test/interpreter/FunctionDeclaration.test.js
This allows a custom `Substitute` function to be created that accepts more than the default three arguments!  Pretty handy.
> fix(interp): Allow named functions to shadow global stdlib functions

- package.json
- src/interpreter/index.ts
- src/stdlib/File.ts
- test/e2e/StdLib.test.js
- test/e2e/resources/stdlib/files.brs
- test/stdlib/File.test.js
- yarn.lock
This implements the file functions not already covered with the exception of MatchFiles, which I'll move to another issue.  Most of these functions wrap existing fs functions that have similar behavior (ex. not allowing deletion of a non-empty directory).  
Functions defined include:
* ListDir
* CopyFile
* MoveFile
* DeleteFile
* DeleteDirectory
* CreateDirectory
* FormatDrive
Although, _FormatDrive_ is stubbed as not implemented.  
Closes #87
> implements file I/O operations for issue #87

- src/Stringify.ts
- src/index.ts
- src/interpreter/index.ts
All it did was call `.toString()` on things.  That doesn't really warrant a separate function and module 🤷‍♂️.  It seemed like a good idea at the time!
> chore(cleanup): Remove unnecessary `Stringify` module

- .travis.yml
We're in a neat time period where `node` 6.x is in the "maintenance LTS" phase, and both 8.x and 10.x are in the "active LTS" phase [[source]](https://github.com/nodejs/Release/tree/887d5e73cba5b3f9225dd81625f97a0f288e2079#release-schedule).  Let's make sure this project still works on all those versions!
> chore(infra): Test on node 6, 8, and 10

- src/brsTypes/index.ts
- src/interpreter/index.ts
- test/interpreter/Arithmetic.test.js
- test/interpreter/BooleanAlgebra.test.js
- test/interpreter/Comparison.test.js
Comparing runtime values for equality to `invalid` is the only way to check if a value exists, so it needs to be supported in this implementation.  This also prevents continued execution if a type mismatch _is_ encountered.
fixes #112
> fix(interp): Allow all types to be compared for equality to `invalid`

- test/e2e/resources/stdlib/math.brs
This line looks like it was copied from `../strings.brs` by accident.
(Also the GitHub web editor adds a newline to files, apparently.)
/me goes back to lurking
> Remove stray line from math.brs

- src/interpreter/index.ts
While working on `createObject("roTimespan")`, I noticed when calling a method it wasn't logging or returning anything. With @sjbarag's help it was discovered that were just weren't showing runtime errors in the interpreter. Now we should show them so we know what's going on! Useful!
> Add BRS runtime error handling

- src/parser/Parser.ts
- test/parser/expression/Function.test.js
- test/parser/expression/__snapshots__/Function.test.js.snap
[rodash](https://github.com/Tubitv/rodash) currently causes a parse
failure for its oneliner anonymous function form:
```brightscript
fn = Function(x): return x: End FUnction
```
I forgot to allow `:` in function declarations instead of newlines!
fixes #133
> fix(parse): Allow ':'-separated function expressions

- package.json
- yarn.lock
TypeScript 2.x seems to have some weird behavior where a destructured import of a type alias results in `import("../../../../../../path/to/file")` appearing wherever that alias is used.  This caused some of my directory structure to leak into the exported type files.  Now everyone knows I have a `src/` directory :sob:.
Upgrading to TypeScript 3 seems to fix that, and I wanted to do that eventually anyway.
fixes #137
> chore(infra): Upgrade to typescript@3

- .npmrc
This package is actually published to npmjs.com and mirrored to
yarnpkg.com instead of directly to yarnpkg.com.
> fix(build): Use npmjs.com as registry instead of yarnpkg.com

- package.json
- test/lexer/Lexer.test.js
- yarn.lock
Nothing too important here, but jest now requires `it.todo` instead of `it(description);`.  Easy-peasy.
> chore(deps): Upgrade dependencies

- .circleci/config.yml
- package.json
- yarn.lock
Travis isn't unusably slow, but circleci is _significantly_ faster for linux builds.  Circle tends to finish four node versions' worth of testing in ~40 seconds, and Travis finishes three in ~3 minutes.
> chore(ci): Enable circleci for builds

- src/parser/Parser.ts
- test/parser/controlFlow/For.test.js
- test/parser/controlFlow/ForEach.test.js
- test/parser/controlFlow/__snapshots__/For.test.js.snap
- test/parser/controlFlow/__snapshots__/ForEach.test.js.snap
While not specified anywhere in its public documentation, the Reference BrightScript Implementation (RBI) allows `next` to be used to terminate `for` and `for each` loops everywhere `end for` would normally be used.  Note that `next` can't be used like `continue` would in other languages (i.e. to stop execution of the loop's block for the current loop variable and move to the next value) - it's a strict synonym for `end for` in BrightScript.
fixes #145
> fix(parse): Allow `next` keyword as synonym for `end for`

- src/lexer/ReservedWords.ts
- test/e2e/resources/for-loops.brs
- yarn.lock
The parser's test passed because it used hardcoded tokens for its input, but there were no end-to-end tests to make sure this actually worked in practice.  Whoops!
Thanks for letting me know, @TwitchBronBron :)
fixes #145 
(again)
> fix(lexer): Add `next` as a keyword

- test/e2e/Functions.test.js
- test/e2e/resources/function/scoping.brs
I forgot to re-enable it once `type()` was implemented!
> test(e2e): Re-enable scoping end-to-end test

- src/parser/Parser.ts
- test/e2e/Iterables.test.js
- test/e2e/resources/arrays.brs
- test/e2e/resources/associative-arrays.brs
- test/parser/statement/Set.test.js
- test/parser/statement/__snapshots__/Set.test.js.snap
Due to the fact that the `=` token is ambiguous without context (i.e. "is it an assignment or comparison?"), assignments get parsed as binary operations and transformed into assignments after the binary operation's been completely parsed.  Dotted and indexed "set" statements (e.g. `foo.bar = "baz"`) required a bit of additional parsing logic when they were added.  Since assignment operators like `+=` are unambiguously used in statements only, there was yet more parsing logic required to handle assignment operators when the left-hand side is a dotted or indexed set.
This should take care of it though!
fixes #173
> feat(parse): Allow assignment operators in set statements

- src/parser/Parser.ts
- test/e2e/Iterables.test.js
- test/e2e/resources/associative-arrays.brs
- test/parser/expression/Function.test.js
- test/parser/statement/Set.test.js
- test/parser/statement/__snapshots__/Set.test.js.snap
The parser was a little bit too greedy when attempting to detect set statements, which I should have noticed with the weird workarounds in that function.  Now that we're _not_ trying to read an entire expression as the left-hand side of a set statement (e.g.  `foo + bar *= 3`), that complication can be removed.
Arbitrarily complex expressions are now supported on the right-hand side of a set statement, e.g. `foo.bar = true and false or 3 > 4`
fixes #156
> fix(parser): Allow complex expressions on RHS of set statements

- src/interpreter/index.ts
- src/parser/Parser.ts
When the function arguments had their `name` property converted to an object containing location, these spots were missed, causing the error messages to contain `'[object Object]'` instead of the actual argument name
Fixes #196
> Use `name.text` for argument error messages.

- src/lexer/Lexer.ts
- test/lexer/Lexer.test.js
Fix issues in the parser with multiple spaces between two-word keywords (like `for each`, `exit while`, etc). 
I also verified that tabs are treated the same as spaces, so I added support for tabs between these keywords as well. This program is an example (replace `\t\t` with actual tab chars):
```
sub SayHi(message as string)
for \t\t each num in [1,2,3]
print num
end for
end sub
```
Fixes #202 
Fixes #201
> Fix for each space

- src/lexer/Lexer.ts
- src/parser/Parser.ts
- test/parser/statement/Function.test.js
- test/parser/statement/__snapshots__/Function.test.js.snap
Adds parser support for type designators (i.e. a trailing `$` `%` `#` `!` after a variable identifier). This will still need to be implemented in the runtime at a later time. 
All function, variable, and parameter identifier tokens are permitted to end with a type designator. Then, in the parser, we enforce that function identifiers are NOT allowed to end with a type designator. 
Fixes #162
> Parser support type designators

- src/lexer/Lexer.ts
- test/lexer/Lexer.test.js
The lexer was not properly tokenizing bitshift assignment operators. However, the parser DOES support them, so the only change necessary was the lexer.
This does not implement the runtime functionality.
Fixes #172
> Support bitshift assignment operators in the lexer

- src/parser/Parser.ts
- test/parser/expression/AssociativeArrayLiterals.test.js
- test/parser/expression/__snapshots__/AssociativeArrayLiterals.test.js.snap
The parser does not properly parse objects with properties separate by colons: `obj = {x:0 : y: 1}`. This PR resolves that issue.
Fixes #195
> Support colons as separators for AA properties

- src/parser/Parser.ts
- test/parser/expression/Call.test.js
- test/parser/expression/__snapshots__/Call.test.js.snap
Sometimes a parse error causes the `block` function to consume all of the remaining tokens. This PR fixes that issue by discarding the line, which should drastically improve parse error recovery.
Fixes #157
> Better single line recovery

- src/brsTypes/components/BrsObjects.ts
- src/brsTypes/components/Regex.ts
- src/brsTypes/index.ts
- test/brsTypes/components/Regex.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roRegex.brs
This feature implements all methods of the [ifRegex](https://sdkdocs.roku.com/display/sdkdoc/ifRegex) interface. 
Although javascript's `RegExp` doesn't fully support PCRE, as Brightscript does, it gives `brs` the ability to support most of the common regex use cases.
All flags in [roRegex](https://sdkdocs.roku.com/display/sdkdoc/roRegex) but "x" should be supported.
> feat(stdlib): Implement createObject("roRegex")

- src/parser/Parser.ts
- test/parser/statement/Increment.test.js
- test/parser/statement/__snapshots__/Increment.test.js.snap
Thanks for catching that, @TwitchBronBron!
fixes #223
> fix(parse): Consume newlines and `:`s after `++` and `--`

- src/parser/Parser.ts
- test/parser/expression/Function.test.js
- test/parser/statement/Function.test.js
While `sub` is conventionally used only for functions with `void` return types, the Reference BrightScript Implementation (RBI) allows non-void return types to be declared on `sub`s, e.g.:
```brightscript
sub main()
print getFive()
end sub
sub getFive() as integer
'             ~~~~~~~~~~
'             This is valid in RBI!
return five
end sub
```
fixes #220
> fix(parse): Allow `sub` declarations with return-type specifications

- test/cli/cli.test.js
The cli tests fail when running on windows. I think it has to do with a js file not being executable on its own. This PR fixes that.
> On windows, spawn needs to call node in order to execute js files.

- src/lexer/Lexer.ts
- test/lexer/Lexer.test.js
As in JavaScript, it's perfectly valid to use `.123` or `12.` as floating-point literals.  Thanks for catching this, @triwav and @TwitchBronBron!
fixes #178
fixes #210
> fix(lex): Allow digits before and after `.` to be elided

- package.json
- src/parser/Parser.ts
- test/parser/statement/PrintStatement.test.js
- test/parser/statement/__snapshots__/PrintStatement.test.js.snap
> Empty print statement

- package.json
- src/lexer/Lexeme.ts
- src/lexer/ReservedWords.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- test/lexer/Lexer.test.js
- test/parser/statement/Stop.test.js
- test/parser/statement/__snapshots__/Stop.test.js.snap
> Stop statement syntax support

- src/lexer/Lexer.ts
- test/lexer/Lexer.test.js
The two-word variants `#else if` and `#end if` were already supported, but I didn't realize the single-word versions were valid in RBI!  Now they're valid here too.
> fix(lex): Allow single-word #elseif and #endif

- src/preprocessor/Manifest.ts
This allows any caller to pass in the manifest file's contents, rather than depending on its physical location. This will help my languageserver because the manifest file changes are loaded into memory and are not always saved to disk right away...but we want to reflect those changes instantly.
> Break out manifest parsing into own function

- src/brsTypes/components/RoRegex.ts
- test/brsTypes/components/RoRegex.test.js
While JavaScript uses `undefined` for regex groups it doesn't find, BrightScript appears to use an empty string!  Luckily fixing that is pretty simple 😄
> fix(RoRegex): Use empty string instead of Invalid for not-found groups

- src/brsTypes/Boxing.ts
- src/brsTypes/BrsType.ts
- src/brsTypes/components/BrsComponent.ts
- src/brsTypes/components/BrsObjects.ts
- src/brsTypes/components/RoArray.ts
- src/brsTypes/components/RoAssociativeArray.ts
- src/brsTypes/components/RoRegex.ts
- src/brsTypes/components/RoString.ts
- src/brsTypes/components/Timespan.ts
- src/brsTypes/components/index.ts
- src/brsTypes/index.ts
- src/interpreter/AutoBox.ts
- src/interpreter/index.ts
- test/brsTypes/String.test.js
- test/brsTypes/components/RoArray.test.js
- test/brsTypes/components/RoAssociativeArray.test.js
- test/brsTypes/components/RoString.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roString.brs
- test/interpreter/Comparison.test.js
`roString` — specifically the methods described in `ifStringOps` — is one of the most often-used non-SceneGraph types in the BrightScript language.  It's not necessarily directly created by BrightScript authors, but it gets created whenever `foo.split("/")` or `bar.encodeUriComponent()` are called due to the reference implementation's automatic boxing rules.  Basically, if you use a boxable primitive like an object, it'll get automatically boxed for you, and the temporary boxed value will be destroyed at the end of the operation.
This PR implements the `ifStringOps` functions on a new `roString` type, and includes that automatic boxing behavior.
> feat(stdlib,interp): Implement autoboxing and roString (ifStringOps only)

- src/brsTypes/Callable.ts
- src/index.ts
- src/interpreter/index.ts
- src/lexer/ReservedWords.ts
- src/preprocessor/Manifest.ts
- src/preprocessor/index.ts
- src/stdlib/File.ts
- src/stdlib/Run.ts
- src/stdlib/index.ts
- test/e2e/StdLib.test.js
- test/e2e/resources/stdlib/run.brs
- test/e2e/resources/stdlib/runme.brs
- test/stdlib/File.test.js
- test/stdlib/Run.test.js
RBI's standard library includes a `Run` function, used to allow a BrightScript file to execute another BrightScript file given its full file path (using a `main` function as its entry point).  That's real handy, as it'll allow several files with `main` functions to co-exist, as long as they're not all in the `source/` directory.
> feat(stdlib,e2e): Implement global `Run` function

- package.json
- src/global.d.ts
- src/stdlib/File.ts
- test/e2e/StdLib.test.js
- test/e2e/resources/stdlib/files.brs
- test/stdlib/File.test.js
- yarn.lock
`MatchFiles` is a pretty interesting function, in that it (combined with the global `Run` implemented in #149) allow for some _very_ dynamic execution patterns!  RBI supports it, so now we do too.
fixes #107
> feat(stdlib): Implement global MatchFiles function

- src/brsTypes/components/RoSGNode.ts
- test/brsTypes/components/RoSGNode.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roSGNode.brs
This PR implements 6 of the most used functions in `ifSGNodeChildren` interface:
- appendChild()
- getChildCount()
- getChildren()
- removeChild()
- getParent()
- createChild()
> Implement if sg node children

- src/brsTypes/components/RoSGNode.ts
- test/brsTypes/components/RoSGNode.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roSGNode.brs
This PR implements 6 of the most used functions in ifSGNodeField interface:
- setField
- addFields
- getField
- addField
- setFields
- removeField
- update (This made the more sense to be implemented as part of the fields since it isn't related with the ifSGNodeChildren)
I'm still working on the `observeField` implemented but I want to do a checkpoint here since I've changed quite a bit the RoSGNode class.
> Implement ifSGNodeField interface

- src/parser/Parser.ts
- src/parser/Statement.ts
- test/parser/controlFlow/__snapshots__/For.test.js.snap
- test/parser/controlFlow/__snapshots__/ForEach.test.js.snap
- test/parser/controlFlow/__snapshots__/If.test.js.snap
- test/parser/controlFlow/__snapshots__/While.test.js.snap
- test/parser/expression/__snapshots__/AssociativeArrayLiterals.test.js.snap
- test/parser/expression/__snapshots__/Call.test.js.snap
- test/parser/expression/__snapshots__/Function.test.js.snap
- test/parser/statement/Block.test.js
- test/parser/statement/__snapshots__/Block.test.js.snap
- test/parser/statement/__snapshots__/Function.test.js.snap
- test/parser/statement/__snapshots__/Goto.test.js.snap
- test/parser/statement/__snapshots__/Increment.test.js.snap
- test/parser/statement/__snapshots__/LibraryStatement.test.js.snap
- test/parser/statement/__snapshots__/Misc.test.js.snap
- test/parser/statement/__snapshots__/ReturnStatement.test.js.snap
- test/parser/statement/__snapshots__/Set.test.js.snap
- test/parser/statement/__snapshots__/Stop.test.js.snap
Updates `Stmt.Block` locations to include surrounding whitespace, and renamed `startingLocation` to `location`. 
Fixes #159
> Block include surrounding whitespace

- yarn.lock
Still gotta move to `eslint` over `tslint`, but that's a problem for future-me.
Thanks, `yarn upgrade`!
> chore(deps): Upgrade all dependencies

- src/brsTypes/Callable.ts
- src/extensions/RunInScope.ts
- src/extensions/index.ts
- src/extensions/mockComponent.ts
- src/index.ts
- src/interpreter/Environment.ts
- src/interpreter/index.ts
- src/stdlib/index.ts
- test/extensions/RunInScope.test.js
While the standard `Run` function allows arbitrary files to be executed, they're executed in their own empty scope!  That leads to a whole lot of repeated lexing, parsing, etc. of the `source/` tree when running unit tests, so we can expose a custom version of `Run` that keeps the previous values in-scope, deletes the previous `main` function, and otherwise executes the requested files the same way.
> feat(extension): Add _brs_.runInScope

- src/brsTypes/Callable.ts
- src/brsTypes/Int32.ts
- src/brsTypes/Int64.ts
- src/brsTypes/components/Timespan.ts
- test/brsTypes/Callable.test.js
- test/brsTypes/Int32.test.js
- test/brsTypes/Int64.test.js
Roku does truncate float to integer (not round) so I also changed the constructor of Int32 and Int64 to correctly mimic the behavior.
fixes #280
> Functions and constructors to auto-convert between Int and Float

- src/brsTypes/components/RoArray.ts
- src/brsTypes/components/RoAssociativeArray.ts
- test/brsTypes/components/RoAssociativeArray.test.js
- test/e2e/resources/components/roArray.brs
- test/e2e/resources/components/roAssociativeArray.brs
Implements `isEmpty()` for `RoArray` and `RoAssociativeArray` (from `ifEnum` interface), and ensures `doesExist()` returns `true` for explicitly `invalid` properties.
fixes #320
> Fixes on roAssociativeArray and roArray

- src/componentprocessor/index.ts
- test/componentprocessor/componentprocessor.test.js
Reordered the child node parsing and added a unit test to support correct parse order.
> Reordering child node parsing in component

- test/brsTypes/components/RoArray.test.js
Not a huge deal, but minimizing unneeded console output is always nice :)
> chore(test): Remove spurious output from RoArray tests

- src/componentprocessor/index.ts
- src/interpreter/index.ts
- src/parser/ComponentScopeResolver.ts
- src/parser/index.ts
- test/componentprocessor/componentprocessor.test.js
- test/e2e/resources/components/scripts/BaseWidget.brs
- test/e2e/resources/components/scripts/NormalWidget.brs
- test/interpreter/Interpreter.test.js
- test/interpreter/resources/scripts/baseComponent.brs
- test/parser/ComponentScopeResolver.test.js
- test/parser/resources/baseComponent.xml
- test/parser/resources/baseComponentTwoScripts.xml
- test/parser/resources/extendedComponent.xml
- test/parser/resources/extendedComponent2.xml
- test/parser/resources/scripts/baseComponent.brs
- test/parser/resources/scripts/extendedComponent.brs
- test/parser/resources/scripts/utilityBase.brs
- test/parser/resources/scripts/utilityExtended.brs
Sorry that this PR is only one commit. Was battling with git to only submit the new additions. Was having trouble due to different commit history.
This PR adds scope resolution for components. Each component will now have an environment with all functions resolved from its extended components. The simple rule with the Roku environment based on our experiments was basically each component is consolidated into a "tier". The tiers then resolve starting from the component that is being created and moving up through the `extends` chain.
This PR does not include calling `init()` currently and will be in the next PR. However we can again have `init()` defined in more than one extending component.
> feat(rsg, components): Flatten functions through component inheritence chain

- src/parser/Parser.ts
- test/preprocessor/Manifest.test.js
- yarn.lock
Just the result of `yarn upgrade-interactive` and choosing everything, then fixing the resulting `prettier` violations.
> chore(deps): Upgrade dependencies & reformat

- src/brsTypes/components/RoSGNode.ts
- src/componentprocessor/index.ts
- src/interpreter/index.ts
- test/componentprocessor/componentprocessor.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/AdvancedWidget.xml
- test/e2e/resources/components/BaseChild.xml
- test/e2e/resources/components/BaseComponent.xml
- test/e2e/resources/components/ExtendedChild.xml
- test/e2e/resources/components/ExtendedComponent.xml
- test/e2e/resources/components/NormalWidget.xml
- test/e2e/resources/components/componentExtension.brs
- test/e2e/resources/components/customComponent.brs
- test/e2e/resources/components/scripts/AdvancedWidget.brs
- test/e2e/resources/components/scripts/BaseChild.brs
- test/e2e/resources/components/scripts/BaseComponent.brs
- test/e2e/resources/components/scripts/ExtendedChild.brs
- test/e2e/resources/components/scripts/ExtendedComponent.brs
- test/e2e/resources/components/scripts/NormalWidget.brs
- test/e2e/resources/components/scripts/SupportScript.brs
These code changes call every `init` method found when creating a component. The calls are made in the following way:
- Init methods found in the children of the component
- Init method of the current component
also this is done starting from the root node in the hierarchy in case that the created component has any extensions.
`non-init` methods are called in the context of the component being created because of the flattening process in #347
> feat(rsg, components): Call init methods when creating components

- src/componentprocessor/index.ts
- test/componentprocessor/componentprocessor.test.js
- test/componentprocessor/resources/unknownExtensionComponent.xml
Long-term we probably don't want to warn-and-fall-back for components that extend something we don't recognize.  The reference implementation considers that a compilation failure, but since we don't yet know about every component in the reference implementation we can't make that assertion!
> fix(rsg): Prevent infinite loop when a node extends an unknown component

- src/parser/Parser.ts
- test/e2e/resources/arrays.brs
- test/e2e/resources/associative-arrays.brs
- test/parser/expression/Indexing.test.js
- test/parser/expression/__snapshots__/Indexing.test.js.snap
While I've never personally used this syntax, the reference BrightScript implementation seems to support a single dot before an indexed property access, i.e.:
```brightscript
a = { foo: 5 }
print a.["foo"] ' => 5
b = [ 1, 2, 4, 8 ]
print b.[1] ' => 2
```
fixes #332
> feat(parse): Allow `.` before indexed property access

- src/brsTypes/Boxing.ts
- src/interpreter/index.ts
- test/e2e/Functions.test.js
- test/e2e/resources/function/return.brs
- test/interpreter/Call.test.js
RBI will automatically box an intrinsic value when it's returned from a function that declares an `as object` return type.  This makes the function behave quite similarly to an `as dynamic` function, in that it can seemingly return any value.  The only difference is that `as dynamic` won't automatically box something like `return false` into an `roBoolean`, while the `as object` variant will!
fixes #359
> fix(interp): Automatically box return values for 'as object' return types

- src/brsTypes/Boxing.ts
- src/stdlib/Json.ts
- test/e2e/resources/stdlib/json.brs
- test/stdlib/Json.test.js
`formatJson` was written far before boxed types were introduced, and it never gained support for them.  Thanks for catching this, @WilliamsMartinezGLB!
fixes #363
> fix(stdlib): Allow formatJson to serialize boxed types

- src/interpreter/index.ts
- test/e2e/StdLib.test.js
- test/e2e/resources/stdlib/global-utilities.brs
- test/interpreter/Call.test.js
Just like with https://github.com/sjbarag/brs/issues/359, function parameters must *also* get automatically boxed.
> fix(interp): Automatically box `as object` function parameters

- src/extensions/Process.ts
- src/extensions/index.ts
- test/e2e/BrsNamespace.test.js
- test/e2e/MultiFile.test.js
- test/e2e/resources/stdlib/_brs_-namespace.brs
- test/extensions/Process.test.js
It's currently impossible to access `argv` from a BrightScript file executed with `brs`!  While it's also impossible via the reference BrightScript implementation, there's basically no concept of argv there -- instead they accept an associative array of arguments from the OS that implements RBI.
Piping `process.argv` into `brs` should enable more interactive uses of BrightScript outside of the reference implementation.  While we _could_ theoretically parse `argv` into an associative array similar to [minimist](https://github.com/substack/minimist)'s output, it's probably best to leave that to BrightScript implementations for now.
> feat(stdlib): Add _brs_.process.argv to mirror node's process.argv

- src/brsTypes/components/RoAssociativeArray.ts
- test/brsTypes/components/RoAssociativeArray.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roAssociativeArray.brs
This fixes issue #370, where RoAssociativeArray.items() wasn't implemented to match the API spec.  Previously it returned an array of key names while the official spec calls for an array of key/value pairs.  
https://developer.roku.com/docs/references/brightscript/interfaces/ifassociativearray.md#items-as-object
Verified E2E test on a Roku device.  
fixes #370
> fixes RoAssociativeArray.items() implementation (#370)

- src/preprocessor/Manifest.ts
- test/preprocessor/Manifest.test.js
We were previously not handling number parsing properly, with two nasty side-effects:
1. Floating-point values were truncated to integer values only (e.g. `"3.14" => 3`)
2. Strings that began with numbers were parsed as numbers and also truncated (e.g. `"1.2.3.4.5" => 1`)
Both of these stemmed from my misreading of the docs for `parseInt`; what I actually wanted was the `Number()` function followed by `Number.isNaN()`!
> fix(manifest): Fix parsing of numbers in manifest

- src/brsTypes/Callable.ts
- test/brsTypes/Callable.test.js
I based this off the [changes made to convert float -> int](https://github.com/underwoo16/brs/blob/7add6ce4dd9826226ea3e1d1ff70f5174aafecff/src/brsTypes/Callable.ts#L262) from this PR: https://github.com/sjbarag/brs/pull/291
fixes https://github.com/sjbarag/brs/issues/384
> bug(interp): Allow Float parameters passed into function signatures expecting Double

- test/componentprocessor/componentprocessor.test.js
Fix a test that fails on windows devices due to using `path.join`. The test passes now by using `path.posix.join` instead as suggested in #393
> Fix path.join bug in test when run on windows.

- src/index.ts
Scripts in components weren't parsed because they couldn't be found, `__dirname` references the path of the actual js script and not the brightscript project were we want to run the tests.
Fixes: #389
> fix(parser): Parse scripts included in components

- src/brsTypes/components/RoSGNode.ts
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/Group.brs
- test/e2e/resources/components/GroupAsChild.xml
I noticed that when you referenced a component as a child and tried to set its fields, it only worked when they were strings. For example:
```
<component name="foo">
<children>
<Group
id="group"
childRenderOrder="renderLast"
opacity="0.2"
/>
<children>
</component>
```
```
foo = createObject("roSGNode", "foo")
group = foo.findNode("group")
print group.childRenderOrder    ' => "renderLast"
print group.opacity                     ' => "1.0" (or whatever default is)
```
This PR fixes that case by finding and using the type of the field being set.
> Fix bug where child fields are always treated as strings

- src/brsTypes/components/ArrayGrid.ts
- src/brsTypes/components/ComponentFactory.ts
- src/brsTypes/index.ts
- test/brsTypes/components/ArrayGrid.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/ArrayGrid.brs
- test/e2e/resources/components/ComponentsAsChildren.xml
This implements the `<ArrayGrid>` component.
I wasn't sure how much of the logic we wanted to add initially, vs. just having a skeleton `ArrayGrid` that could be instantiated in BrightScript. It seems like most of the special logic would come from the `contentNode` field; however, nodes as fields are not yet supported in `brs`, so we can't do too much with it yet.
Let me know what you think!
> feat(stdlib): implement ArrayGrid component

- src/parser/ComponentScopeResolver.ts
This removes a `Promise.reject` that was polluting test case output with tons of these:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
```
In its stead, we have a `console.error`. We _are_ doubling up on the `console.error`s, because we have one for essentially the same issue [over here](https://github.com/sjbarag/brs/blob/master/src/componentprocessor/index.ts#L157-L159), but that's still less verbose/cleaner than the promise rejection error.
> Change promise rejection to console.error

- src/brsTypes/BrsType.ts
There are several shorthand primitive types [in the Roku docs](https://developer.roku.com/docs/references/scenegraph/xml-elements/interface.md). This adds an alias for those types so they get resolved correctly.
> Add shorthand types

- src/brsTypes/components/RoString.ts
- test/brsTypes/components/RoString.test.js
Before, we weren't escaping the `from` value in `string.replace`, which meant that `brs` was throwing an error due to an invalid `RegExp`. This PR adds an escape.
> fix(stdlib): escape from value in string replace

- src/brsTypes/components/BrsComponent.ts
- src/brsTypes/components/RoSGNode.ts
- src/brsTypes/components/RoSGNodeEvent.ts
- src/brsTypes/index.ts
- test/brsTypes/components/RoSGNodeEvent.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/FieldChangeComponent.xml
- test/e2e/resources/components/scripts/FieldChangeComponent.brs
- test/e2e/resources/components/scripts/FieldChangeMain.brs
This implements `RoSGNodeEvent`. Also, when we implemented `onChange` callbacks in #424, I forgot that those callbacks could optionally receive an event. This PR fixes that, so that now `onChange` can receive the event.
> feat(stdlib): add RoSGNodeEvent

- src/brsTypes/components/BrsComponent.ts
- src/brsTypes/components/ComponentFactory.ts
- src/brsTypes/components/ContentNode.ts
- src/brsTypes/components/RoSGNode.ts
- src/brsTypes/index.ts
- test/brsTypes/components/ContentNode.test.js
- test/brsTypes/components/RoSGNode.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/ComponentsAsChildren.xml
- test/e2e/resources/components/scripts/ContentNode.brs
This implements `ContentNode`.
`ContentNode` is a bit unique in how it manages its fields. Like most components, it has a set of built-in fields that it supports. Unlike most other components, these fields are all "hidden" from the node by default. Then, when a field is accessed in any way, it becomes "visible". The unit tests show this behavior as well, but for clarity, here's an example:
```
node = createObject("RoSGNode", "ContentNode")
print node
' Notice that even though ContentNode has dozens of fields, none of them display.
'
' <Component: roSGNode:ContentNode> =
' {
'    change: <UNINITIALIZED>
'    focusable: false
'    focusedchild: invalid
'    id: 
'}
' Getting a field makes it show up (in all caps)
print node.title
print node.count()  ' => 5 (the node now includes title) …
```
> feat(stdlib): implement ContentNode

- src/interpreter/Environment.ts
- test/e2e/BrsMock.test.js
- test/e2e/resources/mockFunctions.brs
This change allows us to mock functions that don't exist in source. This seems somewhat counter-intuitive: why would we let a test implement a function that doesn't exist in source, yet gets called from source code?
The reason is because `brs` doesn't have all the built-in global functions implemented yet, so this unblocks the testing of source code that calls one of those not-yet-implemented functions. The example I was running into was `tr` -- I wanted to test the code that called `tr`, but `tr` isn't implemented, and it also wasn't mockable, so I had no way to test it.
Also, maybe this would be useful for TDD?
Feel free to reject this if `tr` is a one-off situation or there's a better way. I wasn't sure how many other similar cases there were!
> Allow mocking of "unknown" functions

- tsconfig.json
Node 10 is now the oldest supported release, and all versions of node 10 support 100% of the ES2017 spec per https://node.green/#ES2017!  May as well output newer JavaScript :shrug:
> chore(output): Target ES2017

- src/brsTypes/components/RoSGNode.ts
- src/interpreter/index.ts
- test/e2e/resources/components/BaseComponent.xml
Currently, when `getCallableFunction` attempts to resolve a callable field defined on a component's interface, if it is unable to resolve the given function (i.e. it's not implemented in the given component), an exception will be thrown and execution halted. BrightScript, however, silently fails whenever such a situation is encountered, permitting execution to proceed.
This change updates `brs` to mirror the BrightScript behavior such that a warning is logged to stdout, but execution is allowed to proceed, whenever a non-implemented callable field is encountered.
This change resolves https://github.com/sjbarag/brs/issues/448.
> fix(interp,stdlib): getCallableFunction ignores non-implemented functions

- .circleci/config.yml
New non-nighly releases currently rely on @sjbarag to `yarn version` and `yarn publish` locally.  No need for that anymore!  Now anyone with write permission can run:
```
yarn version
git push --follow-tags upstream/master
```
Or, you know, run that through a pull-request and add the appropriate tag after merging.
> feat(build,ci): Automatically publish tagged commits

- src/parser/Parser.ts
- test/e2e/Syntax.test.js
- test/e2e/resources/conditionals.brs
This allows `if` statements with a logical `not` operator, and closes #329.
> fix(parser): make if statements with 'not' work

- src/brsTypes/BrsType.ts
- src/brsTypes/components/RoAssociativeArray.ts
- src/brsTypes/components/RoSGNode.ts
- test/brsTypes/components/ArrayGrid.test.js
- test/brsTypes/components/ContentNode.test.js
- test/brsTypes/components/Font.test.js
- test/brsTypes/components/Group.test.js
- test/brsTypes/components/Label.test.js
- test/brsTypes/components/LayoutGroup.test.js
- test/brsTypes/components/MarkupGrid.test.js
- test/brsTypes/components/Poster.test.js
- test/brsTypes/components/Rectangle.test.js
- test/brsTypes/components/RoSGNode.test.js
- test/brsTypes/components/RoSGNodeEvent.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/scripts/ComponentFields.brs
Before this change, when you had something like this:
```
node = createObject("RoSGNode", "Node")
node.addField("myArray", "assocarray")
node.myArray = { abcd: 1234 }
```
then `brs` would not allow the assignment of `node.myArray = { abcd: 1234 }`. This was because it was reading `node.myArray`'s value kind as `Invalid`, which didn't match the value kind that was being assigned (associative array is an `Object`), so `brs` didn't let the new value get set. This was only happening for arrays and associative arrays because of how `brs` created their initial types.
There were a lot of tests that had to be updated, sorry, I realize this changes a lot of test files!
> fix(rsg): Make types initialize a little better

- test/brsTypes/components/Timer.test.js
This changed as part of #432, which likely didn't include the changes that added Timer (#450).  No worries!
> fix(test): Fix expected output for Timer components

- src/componentprocessor/index.ts
- src/parser/ComponentScopeResolver.ts
This removes a duplicate warning we logged to `stdout` when we encountered an unknown component extension. It's exactly the same scenario, so there's no need to log it twice.
> fix(stdlib): remove duplicate extends warning

- src/Error.ts
- src/interpreter/index.ts
- test/cli/cli.test.js
- test/cli/resources/errors/syntax-error.brs
- test/cli/resources/errors/uninitialized-object.brs
- test/e2e/BrsComponents.test.js
- test/e2e/BrsMock.test.js
- test/extensions/RunInScope.test.js
Just rethrow error: BrsErrors will be silent, other exceptions will be shown.
Ensure errors aren't logged multiple times.
Fixes #444
> fix(err): Silence "Something terrible happened" errors

- README.md
- package.json
- src/extensions/index.ts
- src/extensions/resetMocks.ts
- src/interpreter/Environment.ts
- test/e2e/BrsMock.test.js
- test/e2e/resources/components/ResetMocksComponent.xml
- test/e2e/resources/resetMocks.brs
This allows you to reset mocks for components, functions, or both. Closes #466.
> feat(extensions): enable mock resets

- .github/workflows/pull-request.yaml
GitHub Actions offers higher concurrency limits on free tiers and offers non-linux OSes!  Seems like a win :)
> feat(cicd): Set up GitHub Actions for push & pull_request

- .circleci/config.yml
We'll migrate nightly builds and automatic publishes shortly, but these builds are the primary use for Circle and can be replaced with the GitHub Actions integration introduced via #469.
> chore(ci): Disable circleci builds for push & pull_request

- .github/workflows/nightly-build.yaml
npm/yarn within GitHub Actions won't read `NODE_AUTH_TOKEN` if `registry-url` isn't set!
> fix(nightly): Fix setup-node params to support noninteractive yarn publish

- src/Error.ts
- src/componentprocessor/index.ts
- src/index.ts
- test/componentprocessor/componentprocessor.test.js
- test/componentprocessor/resources/extendedComponent.xml
RBI allows relative paths in <script/> tags, resolved relative to the XML file that contains the element.  We should support that too, because SGDEX makes heavy use of relative paths (also it's really handy :D)
fixes #471
> fix(rsg): Support relative paths in <script/> tags

- .github/workflows/nightly-build.yaml
While `yarn` doesn't seem to look at an environment variable for authentication, it does look at ~/.npmrc and the setup-node action reads an auth token from the `NODE_AUTH_TOKEN` environment variable:
https://github.com/actions/setup-node/blob/59e61b89511ed136a0b17773f07c349fa5c01e8b/src/authutil.ts#L46-L48
All of which is to say this _should_ work now.
I think.
:fingers_crossed:
> fix(ci): Use actions/setup-node to seed auth token in .npmrc

- src/parser/ComponentScopeResolver.ts
- test/parser/ComponentScopeResolver.test.js
Many components can include the same files via `<script/>` tag, and we previously lexed, preprocessed, and parsed those files every time they were encountered in any component.  Even if a component and its extension both import `uri="pkg:/components/foo.brs"`, we'd parse it twice.  Bummer!
We can save a significant amount of time by memoizing that lexing, preprocessing, and parsing process across components.
> feat(perf): Memoize component scope resolution lexing and parsing

- src/interpreter/Environment.ts
I noticed on the most recent version of `roca` (0.10.1) and the nightly build version of `brs`, running tests didn't work (no tests ran at all). It appears that we were doing a copy-by-reference operation instead of copy-by-value, which was causing the tests to not run. That change was added in [this commit](https://github.com/sjbarag/brs/commit/c3d417521a1109ab9d24966aec75704c64c86e98#diff-ab5e0cb216fac83164743862c64250b3R259), which hasn't been released outside of nightly builds yet.
> fix(stdlib): make tests run again

- src/extensions/mockComponentPartial.ts
- src/interpreter/Environment.ts
- test/e2e/BrsComponents.test.js
- test/e2e/BrsMock.test.js
- test/e2e/resources/components/ComponentMockFunctions.xml
- test/e2e/resources/components/ComponentWithoutMockFunctions.xml
- test/e2e/resources/components/scripts/ComponentMockFunctions.brs
- test/e2e/resources/components/scripts/ComponentWithoutMockFunctions.brs
- test/e2e/resources/components/scripts/MockFunctionsMain.brs
- test/e2e/resources/components/scripts/MockFunctionsUtils-C.brs
We currently conflate module-scoped mock functions (`mockComponentPartial`) with universally scoped mock functions (mocks that override any function of the same name, at every scope level above function-scope). This causes issues when the universal mocks aren't copied from environment to environment.
This PR separates scoped vs. unscoped function mocks.
> fix(exts,mocks): differentiate between scoped and unscoped function mocks

- src/stdlib/File.ts
- test/stdlib/File.test.js
Currently, if you use a global file function on a `"pkg:/"` uri, we are not prepending the URI with the project root directory. This means that if you used `ListDir("pkg:/")`, you would actually get all the files in _the user's_ `/` directory, not the project directory. This PR fixes that.
> fix(stdlib): URIs with pkg protocol are scoped to project dir

- src/brsTypes/Double.ts
- src/brsTypes/Float.ts
- src/brsTypes/Int32.ts
- src/brsTypes/components/RoSGNode.ts
- test/brsTypes/components/RoSGNode.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roSGNode.brs
In issue #508 setting numbers on fields that didn't match the field type were ignored because the check to compare types didn't take numbers into account. 
This updates that check to allow assigning numbers to any number-based field by converting it to the proper type. 
Note, I've updated all number constructors to accept long to make the conversion simpler (so _getValue()_ from a number can be applied to any other number). 
fixes #508
> fix(rsg): Cast numbers to proper field types

- src/LexerParser.ts
- src/parser/ComponentScopeResolver.ts
This pulls the statement memoization into the lexer-parser function instead of the component scope resolver class. After we resolve component scopes, [we then lex and parse](https://github.com/sjbarag/brs/blob/master/src/index.ts#L66) what ends up being a lot of the same files, but without the memoization benefits. Also, this sets us up for the incoming code coverage work, part of which will be lexing and parsing all the same files.
> feat(perf): further memoize lexing and parsing

- package.json
- src/parser/Parser.ts
- test/e2e/Syntax.test.js
- test/e2e/resources/conditionals.brs
- test/parser/controlFlow/If.test.js
- test/parser/controlFlow/__snapshots__/If.test.js.snap
- test/parser/expression/__snapshots__/Call.test.js.snap
- test/parser/statement/Block.test.js
- test/parser/statement/__snapshots__/Block.test.js.snap
- test/parser/statement/__snapshots__/Function.test.js.snap
- test/parser/statement/__snapshots__/Goto.test.js.snap
- test/parser/statement/__snapshots__/LibraryStatement.test.js.snap
- test/parser/statement/__snapshots__/Misc.test.js.snap
- test/parser/statement/__snapshots__/Stop.test.js.snap
`:` appears to be a valid statement separator for nearly all cases -- including the branches of a single-line `if` statement!  This also solves an off-by-one error in some location tracking logic, likely caused by the fact that editors perfer one-indexing and our AST (in compliance with ESTree) uses zero-indexing.
As a side benefit, this includes a `test:debug` npm script.  I've been using it for a while and keep forgetting to publish it.  It starts `jest` and immediately pauses for a debugger to attach, allowing for interactive debugging without having to remember a bunch of `jest` arguments.  Pretty handy!
fixes #481
> fix(parse): Allow multiple statements in single-line `if` branches

- src/parser/Parser.ts
- test/e2e/Syntax.test.js
- test/e2e/resources/while-loops.brs
- test/parser/controlFlow/While.test.js
- test/parser/controlFlow/__snapshots__/If.test.js.snap
- test/parser/controlFlow/__snapshots__/While.test.js.snap
I'd accidentally broken nested-block parsing in #510!  This fixes that and ensures that `block()` always consumes the block-closing token.
> fix(parse): Restore nested block parsing

- src/parser/ComponentScopeResolver.ts
This resolves bug #519 by swapping the node and node parent's places in the message string. See issue for incorrect and correct behavior. 
closes #519
> fix: Change inheritance warning to correct names (#519)

- src/Error.ts
- src/brsTypes/components/RoSGNode.ts
- src/interpreter/TypeMismatch.ts
- src/interpreter/index.ts
- src/parser/BlockEndReason.ts
- test/e2e/resources/components/roSGNode.brs
This exposed a circular dependency between `brsTypes/` `interpreter/index.ts`, and `Error.ts`, resolved by extracting `TypeMismatch.ts` to the `interpreter/` tree since it's currently only used at BrightScript runtime.
fixes #508
> fix(interp): Allow return statements in observeField callbacks

- src/brsTypes/components/RoSGNode.ts
- test/brsTypes/components/RoSGNode.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roSGNode.brs
Fixes #523 where it seems _findNode()_ always returns invalid if passed an empty string for an id even if nodes exist with an empty id.
> fix(rsg): Return invalid when findNode passed empty string

- src/brsTypes/components/RoSGNode.ts
- test/brsTypes/components/RoSGNode.test.js
- test/e2e/Observers.test.js
- test/e2e/resources/observers/components/Observer.brs
- test/e2e/resources/observers/components/Observer.xml
- test/e2e/resources/observers/components/Observer2.xml
- test/e2e/resources/observers/components/UnscopedObserversTestBed.brs
- test/e2e/resources/observers/components/UnscopedObserversTestBed.xml
- test/e2e/resources/observers/unscoped-main.brs
`roSGNode#unobserveField` unsubscribes _all_ nodes subscribed to that field, regardless of subtype, when they subscribed, etc.  It's pretty dangerous, but available in the standard library.
> feat(rsg): Implement unobserveField

- src/brsTypes/components/RoString.ts
- test/brsTypes/components/RoString.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roString.brs
The `roString` object only supported the `setString` with one overload, I added a second overload so the method is supported on both `ifString` and `ifStringOps` interfaces
Closes #515
> feat(rsg): Added setString method of ifString interface

- src/brsTypes/components/BrsObjects.ts
- src/brsTypes/components/RoString.ts
- test/brsTypes/components/RoString.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roString.brs
I found that when creating an string like this:
```
str = createObject("roString")
```
The intrinsic string doesn't have initial value because we were always expecting a second argument in the `createObject` syntax, then when we tried to use methods like `appendString` to the object they won't work because there is no initial string.
I made optional the argument in the `RoString` class constructor so it doesn't break the string boxing functionality but at the same time makes things consistent with the Roku implementation of `roString` which doesn't take a second argument.
Thanks to @adheus who find the bug
Fixes #513
> fix(rsg): Adds optional arg to RoString constructor

- src/interpreter/index.ts
- src/parser/Parser.ts
- src/parser/Statement.ts
- test/e2e/Syntax.test.js
- test/e2e/resources/dim.brs
- test/interpreter/Dim.test.js
- test/parser/statement/Dim.test.js
This implements the dim statement for as requested for #283. It doesn't match Roku's spec exactly as Roku's dim will leave the bottom-level arrays unexpanded but resizeable. When brs supports resizeable arrays (#530) we can come back and update this code to match the spec.
> implement dim statement (#283)

- README.md
- src/extensions/mockFunction.ts
- test/e2e/BrsMock.test.js
- test/e2e/resources/components/scripts/BrsMockFunctions.brs
- test/extensions/MockFunction.test.js
This implements a `MockFunction` spy that gets returned from `_brs_.mockFunction`. The spy keeps track of the calls and return values of the mocked function. The API for it is inspired by [Jest's mockFn API](https://jestjs.io/docs/en/mock-function-api).
> feat(mocks): return a spy from _brs_.mockFunction

- test/e2e/BrsMock.test.js
Removes the `.only` that I mistakenly left in the code in #541 😢
> fix(test): remove .only from test case

- bin/cli.js
- src/componentprocessor/index.ts
- src/index.ts
- src/interpreter/index.ts
- test/componentprocessor/componentprocessor.test.js
Allows directories to search for `.xml` files to be configurable. Closes #501.
> feat(components): configurable directories for component search

- src/parser/Expression.ts
- src/parser/Statement.ts
- test/e2e/__snapshots__/Coverage.test.js.snap
- test/parser/controlFlow/__snapshots__/If.test.js.snap
- test/parser/expression/__snapshots__/AssociativeArrayLiterals.test.js.snap
- test/parser/expression/__snapshots__/Call.test.js.snap
- test/parser/expression/__snapshots__/Function.test.js.snap
- test/parser/statement/__snapshots__/Block.test.js.snap
- test/parser/statement/__snapshots__/Function.test.js.snap
- test/parser/statement/__snapshots__/Goto.test.js.snap
- test/parser/statement/__snapshots__/Increment.test.js.snap
- test/parser/statement/__snapshots__/LibraryStatement.test.js.snap
- test/parser/statement/__snapshots__/Misc.test.js.snap
- test/parser/statement/__snapshots__/ReturnStatement.test.js.snap
- test/parser/statement/__snapshots__/Set.test.js.snap
- test/parser/statement/__snapshots__/Stop.test.js.snap
- Rename Function.end to Function.endKeyword
AST nodes should not have a start or end property.
https://github.com/eslint/eslint/pull/8984
> fix: minor naming collision with eslint/estree spec

- src/brsTypes/components/RoSGNode.ts
- test/brsTypes/components/RoSGNode.test.js
Fix `roSGNode#delete` and `roSGNode#removeField` so that they ignore case
> fix(stdlib): roSGNode#delete and roSGNode#removeField ignore case

- src/brsTypes/components/RoSGNode.ts
- src/interpreter/Environment.ts
- test/e2e/CallFunc.test.js
- test/e2e/resources/components/call-func/scripts/main.brs
Yep, you guessed it... more `callFunc` updates! This time, we need to account for mocked components in `callFunc` calls.
> fix(mocks, stdlib): mocked component callFunc works now

- src/brsTypes/components/RoRegex.ts
- test/e2e/resources/components/roRegex.brs
Previously, if you tried to call `RoRegex#matchAll` or `RoRegex:replaceAll` multiple times using the same `RoRegex` instance, a Javascript error would be thrown because the `g` flag appeared multiple times in the Javascript regex constructor. This PR fixes that.
> fix(stdlib): only append flag once to RoRegex

- .github/workflows/pull-request.yaml
- CONTRIBUTING.md
- docs/AddingComponents.md
Remove hurtful language by following the example of git [1] and GitHub [2], i.e. rename `master` to `main`.
[1] https://lore.kernel.org/git/pull.783.git.1604829561838.gitgitgadget@gmail.com/
[2] https://github.com/github/renaming
> fix(infra): Rename default branch from `master` to `main`

- src/preprocessor/Manifest.ts
- test/preprocessor/Manifest.test.js
Numbers are allowed in RBI's `manifest` file, but `brs` used to lose precision by parsing them as numbers.  This caused some subtle differences when a `manifest` was re-serialized after parsing, in which `1.0` was represented only as `1`.  It's unclear whether or not this caused issues with applications run in RBI using that rewritten `manifest`, but this was originally reported back in July 2019.  Stop parsing `manifest` values as numbers to prevent precision loss.
fixes #279
> fix(manifest): BREAKING-CHANGE Prevent precision loss in parsed manifest

- src/interpreter/Environment.ts
- src/interpreter/index.ts
- test/e2e/BrsComponents.test.js
- test/e2e/BrsMock.test.js
This removes unnecessary warnings so that test output isn't polluted with them.
> fix(interp): Remove unnecessary warnings

- src/index.ts
- src/stdlib/Localization.ts
Apparently I forgot how async code works. This fixes how we load the translation files, so that we actually _wait_ for them to load before executing.
> fix(stdlib): wait for async translations

- src/brsTypes/components/RoArray.ts
- test/brsTypes/components/RoArray.test.js
Refactors roArray sort() and sortBy() so it more closely matches what Roku actually does.
Fixes #591
**array.sort()** example: 
```
Brightscript Debugger> 
arr=["a", 1, ["sub", "array"], 9, 10, "B", {obj: "foo"}, {obj: "bar"}, false, "c", true, false]
Brightscript Debugger> 
arr.sort()
Brightscript Debugger> 
?arr
<Component: roArray> =
[
1
9
10
"B"
"a"
"c"
<Component: roAssociativeArray>
<Component: roAssociativeArray>
<Component: roArray>
false
true
false
]
Brightscript Debugger> 
?arr[6]
<Component: roAssociativeArray> =
{
obj: "foo"
}
Brightscript Debugger> 
?arr[7]
<Component: roAssociativeArray> =
{
obj: "bar"
}
Brightscript Debugger> 
```
**Mixed Arrays seem to get sorted in this order (tested with Roku OS 9.4):
1. numbers in numeric order
2. strings in alphabetical order,
3. …
> Fixes many sorting issues with mixed arrays (fixes #591)

- README.md
- src/extensions/GetStackTrace.ts
- src/extensions/index.ts
- src/interpreter/index.ts
- src/lexer/Token.ts
- test/e2e/GetStackTrace.test.js
- test/e2e/resources/components/stack-trace/@external/package/utils.brs
- test/e2e/resources/components/stack-trace/main.brs
- test/e2e/resources/components/stack-trace/print.brs
- test/extensions/getStackTrace.test.js
This implements an extension `_brs_.getStackTrace`, which, as you might expect, gets the stack trace.
Also, I cleaned up the `README` a little -- reorganized the extensions alphabetically.
> feat(interp,exts): implement stack trace

- src/LexerParser.ts
- src/index.ts
- src/interpreter/index.ts
Using `Object.assign()` without an initial `{}` overwrote values in `defaultExecutionOptions` in a "last overwrite wins" pattern.  This caused the produced interpreter to execute functions like `ListFiles()` relative to the temporary directory the final component library is unzipped into, rather than relative to the process's current working directory.
Use the object spread syntax instead of `Object.assign()` since it's harder to get wrong, and freeze the `defaultExecutionOptions` variable after creation to prevent accidental modification.
> fix(interp): Don't modify defaultExecutionOptions after creation

- README.md
This alphabetizes the "extensions" section of the readme. It also adds function signatures to functions that didn't have them.
> chore(docs): alphabetize extensions on readme

- src/extensions/GetStackTrace.ts
- test/e2e/GetStackTrace.test.js
- test/extensions/getStackTrace.test.js
It probably makes more sense for the stack trace to be formatted so that the 0th element is the most recent. It allows for easier traversal for consumers. This also lines up with [Javascript error stack](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack), for example.
> Reverse stack trace

- src/brsTypes/components/RoSGNode.ts
This fixes a bug where the interpreter throws a type mismatch when `CallFunc` doesn't return a value. Because `CallFunc` has a dynamic return type, the interpreter does not allow void.
> fix(stdlib): callFunc should always return a value

- src/index.ts
- test/e2e/createExecuteWithScope.test.js
- test/e2e/resources/execute-with-scope/in-scope.brs
- test/e2e/resources/execute-with-scope/main.brs
- test/e2e/resources/execute-with-scope/main2.brs
This creates a function that generates an "execution scope" by executing a given set of files. Then, it returns a function that will execute other files in that execution scope.
This is similar to the existing `runInScope` extension in that it allows us to lex/parse a set of files once, then use those results for future executions. The benefit of this, though, is that we can use this capability in JS, whereas `runInScope` is called from Brightscript files.
We can use this in `roca` to run through our test suite in JS, which will allow us more flexibility in reporting, CLI options, and better error handling.
> feat(execution): create function to execute with scope

- docs/NotImplemented.md
Like #601 but for scenegraph!  Add table of scenegraph nodes, their implementation status in `brs`, and additional notes.
fixes #463
> doc: Add table of scenegraph node statuses

- src/brsTypes/components/BrsObjects.ts
- src/brsTypes/components/RoXMLElement.ts
- src/brsTypes/index.ts
- test/brsTypes/components/RoXMLElement.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roXMLElement.brs
supported interfaces:
```
parse
getName
getAttributes
getNamedElementsCi
```
see #282
> Adding support for `RoXMLElement`

- src/brsTypes/components/BrsObjects.ts
- src/brsTypes/components/ComponentFactory.ts
- src/brsTypes/index.ts
- src/parser/ComponentScopeResolver.ts
- src/stdlib/CreateObject.ts
- test/brsTypes/components/ComponentFactory.test.js
- test/e2e/CustomComponents.test.js
- test/e2e/customResources/components/ExtendCustom.brs
- test/e2e/customResources/components/ExtendCustom.xml
- test/e2e/customResources/components/extendCustomMain.brs
- test/stdlib/Runtime.test.js
This is a series of changes that allow other software using BRS as a library to add new BrsComponents or Scenegraph components (PinPad, BusySpinner, etc) at Runtime.
This is useful, for example, if another piece of software wanted to implement video playback or Draw2d functionality, and then it could do so by implementing those components locally and still leverage the BRS project.
While the BRS project is very useful as a parser/lexer/interpreter, it does not do any emulation or real-world display of Scenegraph nodes. If there were another piece of software the wanted to leverage BRS, but do that display piece, then being able to override/extend the built in implementation would be a good thing.
> feat(rsg): Support adding new BrsObjects at Runtime

- src/lexer/Lexer.ts
- test/lexer/Lexer.test.js
By using an identifier in a BrightScript file as an index into that object, we accidentally leaked non-Token properties on the `KeyWords` JS object from the lexer, e.g. `return KeyWords["constructor"]`.  Use `hasOwnProperty()` to check if an identifier is a BrightScript keyword to avoid returning JavaScript internals as Tokens.
fixes #613
> fix(lex): Allow JS object properties as identifiers

- src/interpreter/index.ts
- src/parser/Parser.ts
- test/e2e/Syntax.test.js
- test/e2e/resources/arithmetic.brs
- test/interpreter/Arithmetic.test.js
- test/parser/expression/PrefixUnary.test.js
- test/parser/expression/__snapshots__/PrefixUnary.test.js.snap
BrightScript, like JavaScript and several other languages, supports a leading `+` sign before numeric literals (and variables, incidentally). Check for `+` tokens when parsing unary expressions, and evaluate them at runtime (no-op).
fixes #227
> fix(parse,interp): Support unary + operator for numbers

- src/lexer/Lexer.ts
- test/lexer/Lexer.test.js
RBI forces all literal numbers to double-precision if they're longer than characters, and also allows such a number to be explicitly designated a double with a trailing `#`.  `brs` didn't.  Look for a trailing `#` when lexing long numeric literals, to avoid treating it like a conditional compilation string.
fixes #616
> fix(lex): Allow explicit double designator on literals > 10 characters

- src/brsTypes/components/RoSGNode.ts
- test/e2e/CallFunc.test.js
- test/e2e/resources/components/call-func/CallFuncTestbed.xml
- test/e2e/resources/components/call-func/scripts/CallFuncTestbed.brs
- test/e2e/resources/components/call-func/scripts/main.brs
When a function is executed via `callFunc(name, ...args)`, we were accidentally losing the hostNode because we use interpreter.inSubEnv with the optional second parameter to pass in a custom environment. That environment is based on the prototype-like environment created for each component's definition, which can't include an accurate hostnode
based on runtime control flow.  Manually set a hostNode when calling functions via `callFunc`.
fixes #585
> fix(rsg): Ensure hostNode set in <function> implementation

- README.md
Whoops, in #625 I wrote a link backwards in markdown. This fixes it.
> fix(docs): fix link to docs site

- src/extensions/mockFunction.ts
- test/e2e/BrsMock.test.js
- test/e2e/resources/components/mocks/functions/main.brs
This improves `_brs_.mockFunction` in a couple of ways:
1. Allow calling without passing a substitute/mock (i.e. implicit mock)
1. Implement `_brs_.mockReturnValue` (named like [jest](https://jestjs.io/docs/en/mock-function-api#mockfnmockreturnvaluevalue))
> feat(mocks): mockFunction improvements

- src/stdlib/String.ts
- test/e2e/StdLib.test.js
- test/e2e/resources/stdlib/strings.brs
This addresses #581, where only floats are accepted by the Str() function. 
**Change**
The implementation for floats and doubles is identical where they need to be converted to a string, and if positive add a space beforehand. The simplest fix was to change the input type to double, so both floats and doubles would be supported. 
Fixes #581
> add double support to Str() (#581)

- src/brsTypes/components/RoString.ts
- test/brsTypes/components/RoString.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roString.brs
fix for #575 issue 
what were done:
- added `isEmpty` to `ifStringOps` interface (is undocumented in roku doc)
- added unit test for imlementation
- added e2e test.
> add isEmpty method to roString

- src/lexer/Lexer.ts
- test/e2e/Syntax.test.js
- test/e2e/resources/printLiterals.brs
- test/lexer/Lexer.test.js
 this PR resolves #627 issue
what were done:
- added support for `%` suffix in integer literals
- added unit test for imlementation(lexer)
- added e2e test.
> fix(lexer): Add support for explicit integer literals

- .github/workflows/nightly-build.yaml
The default behavior for GitHub's `actions/checkout@v2` only fetches the
latest commit [1], so our previous attempts to detect commits "since
last night's nightly build" always failed.  Fetch two commits to make it
possible to detect commits in `main` within the past 25 hours.
[1] https://github.com/actions/checkout/tree/25a956c84d5dd820d28caab9f86b8d183aeeff3d#checkout-v2
> fix(nightly): fetch two commits to detect commits-since-last-build

- src/brsTypes/components/RoSGNode.ts
- test/e2e/RoSGNode.test.js
- test/e2e/resources/components/roSGNode/roSGNode.brs
Fixes https://github.com/sjbarag/brs/issues/644
Fixed by calling `appendChildToParent` instead of `setParent` from `reparent`'s implementation.
> fix(rsg): Reparent does not add child to new parent

- src/brsTypes/BrsType.ts
- src/brsTypes/components/RoString.ts
- test/brsTypes/components/ArrayGrid.test.js
- test/brsTypes/components/ContentNode.test.js
- test/brsTypes/components/Font.test.js
- test/brsTypes/components/Group.test.js
- test/brsTypes/components/Label.test.js
- test/brsTypes/components/LayoutGroup.test.js
- test/brsTypes/components/MarkupGrid.test.js
- test/brsTypes/components/MiniKeyboard.test.js
- test/brsTypes/components/Poster.test.js
- test/brsTypes/components/Rectangle.test.js
- test/brsTypes/components/RoArray.test.js
- test/brsTypes/components/RoAssociativeArray.test.js
- test/brsTypes/components/RoSGNode.test.js
- test/brsTypes/components/Scene.test.js
- test/brsTypes/components/TextEditBox.test.js
- test/brsTypes/components/Timer.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/StdLib.test.js
Fixes #416
It's my first PR here -- please be gentle with me. 😅
OK, so Roku doesn't add quotes to a string only in 1 case: if we're printing a simple string variable:
```
stringVar = "Test string"
? "String variable:"
? stringVar
```
Output:
```
String variable:
Test string
```
I all other cases, Roku adds quotes. Whether it's an array, AA, list, or field of a node:
```
arrayWithString = ["Test string"]
? "Array with string:"
? arrayWithString
?
assocArrayWithString = {
entry: "Test string"
}
? "AA with string:"
? assocArrayWithString
?
listWithString = CreateObject("roList")
listWithString.addTail("Test string")
? "List with string:"
? listWithString
? "type("Chr(34)"Test string"Chr(34)"): "type("Test string")
? "type(listWithString[0]) (!): "type(listWithString[0])
?
nodeWithString = …
```
> Issue #416 toString() method not printing string fields with quotes

- src/parser/ComponentScopeResolver.ts
- test/e2e/BrsComponents.test.js
- test/e2e/Functions.test.js
- test/e2e/resources/components/scripts/BaseComponent.brs
- test/e2e/resources/components/scripts/ExtendedComponent.brs
- test/e2e/resources/components/scripts/SupportScript.brs
- test/e2e/resources/function/casing.brs
In RBI functions with the same name are always overriden (despite the casing) if extending components with the only exception of the `Init` method which is a special case. With this fix, it doesn't matter what convention you use to name your function as it's going to be converted to lowerCase to fix the override issue we were having.
In addition to the fix, I added a test case to functions to verify that casing doesn't matter when naming functions.
Fixes #502
> fix(interpreter): Support case insensitive names for functions in components

- src/brsTypes/components/BrsComponent.ts
- src/brsTypes/components/ComponentFactory.ts
- src/brsTypes/components/RoAssociativeArray.ts
- src/brsTypes/components/RoSGNode.ts
- src/interpreter/index.ts
- test/brsTypes/components/RoAssociativeArray.test.js
- test/brsTypes/components/RoSGNode.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/Iterables.test.js
- test/e2e/RoSGNode.test.js
- test/e2e/Syntax.test.js
- test/e2e/resources/components/roAssociativeArray.brs
- test/e2e/resources/components/roSGNode/roSGNode.brs
solution $629 issue
what were done:
- fixed `CreateObject("roSGNode", "node")`
- added support for `lookupCI` for AA and Nodes
- added UT and e2e tests
resolves #629  
UPD:
- Fixed logic of using/saving keys in AA (saving last key used by `[]`, or lowercase key if accessed by `.`)
> feat(stdlib): Add lookupCI for assocarray and Node

- src/extensions/index.ts
- src/index.ts
- test/extensions/testData.test.js
fix for issue #623 
added `testData` to `_brs_` object
exported new method `resetTestData` for cleaning `testData` before runing test suites(test files)
linked roca PR: https://github.com/hulu/roca/pull/88
> feat(extensions): Add _brs_.testData associative array

- src/brsTypes/components/BrsObjects.ts
- src/brsTypes/components/RoAppInfo.ts
- src/brsTypes/index.ts
- src/extensions/Process.ts
- src/index.ts
- src/interpreter/index.ts
- test/brsTypes/components/RoAppInfo.test.js
- test/e2e/BrsComponents.test.js
- test/e2e/resources/components/roAppInfo.brs
- test/e2e/resources/conditional-compilation/manifest
> feat(stdlib): Implement roAppInfo

- src/index.ts
- test/e2e/createExecuteWithScope.test.js
- test/e2e/resources/execute-with-scope/mock.brs
This resets mocks between executions that share the same base scope, to prevent them from polluting/interfering with each other. Got the idea from the implementation in #646!
Related: https://github.com/hulu/roca/issues/89
> fix(extensions): reset mocks between executions

- src/lexer/Lexer.ts
- src/lexer/Token.ts
- test/lexer/Lexer.test.js
Comment nodes are handy for non-executing tooling, and allow tools like `eslint` to automatically ignore rules based on specific directives. Emit `eslint`-compliant comment nodes from the lexer for consumption by external tools.
> feat(lex): Emit comments from the lexer

- src/componentprocessor/index.ts
- src/parser/Parser.ts
- test/lexer/Lexer.test.js
- yarn.lock
The upgrade from husky 4 to husky 6 will require some manual intervention.  Upgrade all other dependencies to the latest version that still supports node@10.
> chore(deps): Upgrade most dev dependencies

- src/brsTypes/coercion.ts
- test/brsTypes/coercion.test.js
This fixes a bug where if you tried to do:
```brs
sub foo(arg as object) : end sub
sub bar() : end sub
foo(bar) ' runtime error
```
`brs` would throw an ugly error. RBI allows this type-casting, so we should too!
This error was actually getting thrown a bunch in the sister project, https://github.com/hulu/roca, since `brs@0.44.0`, because all the `describe` and `it` functions use the `as object` type for functions.
> fix(interp): allow functions to be typed as objects

- src/brsTypes/components/RoSGNode.ts
In #629 there were a bunch of changes to `RoAssociativeArray` for case-sensitivity, namely preserving key case by default. Because `RoSGNode#update` uses an assoc array and `RoSGNode` stores all its fields lower case, we need to make it _not_ case-sensitive.
> fix(stdlib): make RoSGNode#update case insensitive

- src/brsTypes/Callable.ts
- src/brsTypes/components/RoSGNode.ts
- src/interpreter/ArgumentMismatch.ts
- src/interpreter/Environment.ts
- src/interpreter/index.ts
- test/e2e/CallFunc.test.js
- test/e2e/resources/components/call-func/CallFuncTestbed.xml
- test/e2e/resources/components/call-func/scripts/CallFuncTestbed.brs
- test/e2e/resources/components/call-func/scripts/throw/no-args.brs
- test/e2e/resources/components/call-func/scripts/throw/wrong-arg-type.brs
This fixes a bug where we would throw a _Javascript_ error and display the resulting stack trace to users who used `RoSGNode#callFunc` with incorrect/missing arguments. I also consolidated our "incorrect arguments" error and removed some `finally`s that weren't behaving the way we expected them to.
> fix(stdlib, interp): fix `RoSGNode#callFunc` argument error reporting

- src/LexerParser.ts
- src/interpreter/index.ts
- src/stdlib/Json.ts
- yarn.lock
Major-version upgrades to husky and lint-staged skipped for now, mostly because they don't seem to offer anything significant to warrant upgrading yet.  There's always next time!
> chore(deps): Upgrade most dependencies
